<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

$redis = "";
$gameRedis = "";
$ssdbHost = "";

// test
if (DEV_ENV)
{
    $redis = "127.0.0.1";
    $gameRedis = "127.0.0.1";
    $ssdbHost = "127.0.0.1";
}
else
{
    $redis = "127.0.0.1";
    $gameRedis = "127.0.0.1";
    $ssdbHost = "127.0.0.1";
}
//if (DEV_ENV)
//{
//	$redis = "54.169.242.8";
//	$gameRedis = "54.169.242.8";
//	$ssdbHost = "127.0.0.1";
//}
//else
//{
//	$redis = "192.168.222.3";
//	$gameRedis = "192.168.111.2";
//	$ssdbHost = "127.0.0.1";
//}

$config['redis']['host'] = $redis;
$config['redis']['port'] = 6379;

$config['game_redis']['host'] = $gameRedis;
$config['game_redis']['port'] = 6379;

$config['ssdb']['host'] = $ssdbHost;
$config['ssdb']['port'] = 8888;
$config['ssdb']['timeout_ms'] = 2000;

//我的配置
$config['groups'] = array(
    '0' => '普通用户',
    '1' => '管理员',
    '2' => '普通操作员',
);

$config['statistics'] = array(
    'SMC_M' => '后台',
    'NN_GAME' => '牛牛',
    'ZJH_GAME' => '三张牌',
    'YS_BUY' => '购买',
    'DS_COIN_GIFT' => '送筹码',
    'DS_COIN_GIFT_GIFT' => '送礼物',
    'DS_COIN_ZJH' => '通过Dispatch送筹码',
    'ZJH_AD_COIN_ZJH' => '三张牌广告墙',
    'IAP_COIN_ZJH' => '游戏内购买',
    'USER_WEB_BUY' => '官网购买',
    'SHENZHOUFU_ZJH' => '神州付',
);

//{"key": "total6", "value": "首次游戏人数"}
$config['report_field'] = '[{"key": "total1", "value": "新增设备数"}, {"key": "total2", "value": "新增注册数"}, {"key": "total3", "value": "新增真实注册数"},{"key": "total4", "value": "真实注册且游戏人数"}, {"key": "total5", "value": "新增游客数"}, {"key": "total22", "value": "次日存留"}, {"key": "total23", "value": "第7日存留"},{"key": "total7", "value": "平均在线"},{"key": "total8", "value": "高峰在线"},{"key": "total9", "value": "总用户数"},{"key": "total10", "value": "当日活跃用户"},{"key": "total12", "value": "活跃设备数"},{"key": "total15", "value": "充值总比数"},{"key": "total16", "value": "充值人数"},{"key": "total17", "value": "充值总额"},{"key": "total18", "value": "提现手续费"},{"key": "total_alifee", "value": "支付宝手续费"},{"key": "total19", "value": "提现总额"},{"key": "total20", "value": "七日活跃人数"},{"key": "total21", "value": "七日活跃设备数"},{"key": "total29", "value": "经典斗地主抽水金额"},{"key": "total30", "value": "欢乐斗地主抽水金额"},{"key": "total24", "value": "癞子斗地主抽水金额"},{"key": "total25", "value": "经典三张牌抽水金额"},{"key": "total36", "value": "百人三张牌抽水"},{"key": "total26", "value": "牛牛抽水金额"},{"key": "total27", "value": "看牌抢庄牛牛抽水金额"},{"key": "total28", "value": "捕鱼盈利金额"},{"key": "total35", "value": "电玩城盈利金额"},{"key": "total_lhp", "value": "连环炮盈利金额"},{"key": "total_nnml", "value": "马来牛牛盈利金额"},{"key": "total_sangong", "value": "三公盈利金额"},{"key": "total_hongheidz", "value": "红黑大战盈利金额"},{"key": "total31", "value": "游戏总抽水金额"}]';
$config['caiwu_report_field'] = '[{"key": "total2", "value": "新增注册数"},{"key": "total17", "value": "充值总额"},{"key": "total19", "value": "提现总额"},{"key": "total31", "value": "游戏总抽水金额"}]';

$config['special_admin'] = array(8, 17, 19);
/*
  |--------------------------------------------------------------------------
  | Base Site URL
  |--------------------------------------------------------------------------
  |
  | URL to your CodeIgniter root. Typically this will be your base URL,
  | WITH a trailing slash:
  |
  |	http://example.com/
  |
  | If this is not set then CodeIgniter will guess the protocol, domain and
  | path to your installation.
  |
 */
if (DEV_ENV)
{
//$config['base_url'] = 'http://local_houtai.com/';
//	$config['base_url'] = 'http://localhost:8880/';
    $config['base_url'] = 'http://192.168.1.127:8107/';
}
else
{
	$config['base_url'] = 'http://houtai.yuming.com/';
}

/*
  |--------------------------------------------------------------------------
  | Index File
  |--------------------------------------------------------------------------
  |
  | Typically this will be your index.php file, unless you've renamed it to
  | something else. If you are using mod_rewrite to remove the page set this
  | variable so that it is blank.
  |
 */
$config['index_page'] = '';

/*
  |--------------------------------------------------------------------------
  | URI PROTOCOL
  |--------------------------------------------------------------------------
  |
  | This item determines which server global should be used to retrieve the
  | URI string.  The default setting of 'AUTO' works for most servers.
  | If your links do not seem to work, try one of the other delicious flavors:
  |
  | 'AUTO'			Default - auto detects
  | 'PATH_INFO'		Uses the PATH_INFO
  | 'QUERY_STRING'	Uses the QUERY_STRING
  | 'REQUEST_URI'		Uses the REQUEST_URI
  | 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
  |
 */
$config['uri_protocol'] = 'AUTO';

/*
  |--------------------------------------------------------------------------
  | URL suffix
  |--------------------------------------------------------------------------
  |
  | This option allows you to add a suffix to all URLs generated by CodeIgniter.
  | For more information please see the user guide:
  |
  | http://codeigniter.com/user_guide/general/urls.html
 */

$config['url_suffix'] = '.html';

/*
  |--------------------------------------------------------------------------
  | Default Language
  |--------------------------------------------------------------------------
  |
  | This determines which set of language files should be used. Make sure
  | there is an available translation if you intend to use something other
  | than english.
  |
 */
$config['language'] = 'english';

/*
  |--------------------------------------------------------------------------
  | Default Character Set
  |--------------------------------------------------------------------------
  |
  | This determines which character set is used by default in various methods
  | that require a character set to be provided.
  |
 */
$config['charset'] = 'UTF-8';

/*
  |--------------------------------------------------------------------------
  | Enable/Disable System Hooks
  |--------------------------------------------------------------------------
  |
  | If you would like to use the 'hooks' feature you must enable it by
  | setting this variable to TRUE (boolean).  See the user guide for details.
  |
 */
$config['enable_hooks'] = FALSE;


/*
  |--------------------------------------------------------------------------
  | Class Extension Prefix
  |--------------------------------------------------------------------------
  |
  | This item allows you to set the filename/classname prefix when extending
  | native libraries.  For more information please see the user guide:
  |
  | http://codeigniter.com/user_guide/general/core_classes.html
  | http://codeigniter.com/user_guide/general/creating_libraries.html
  |
 */
$config['subclass_prefix'] = 'MY_';


/*
  |--------------------------------------------------------------------------
  | Allowed URL Characters
  |--------------------------------------------------------------------------
  |
  | This lets you specify with a regular expression which characters are permitted
  | within your URLs.  When someone tries to submit a URL with disallowed
  | characters they will get a warning message.
  |
  | As a security measure you are STRONGLY encouraged to restrict URLs to
  | as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
  |
  | Leave blank to allow all characters -- but only if you are insane.
  |
  | DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
  |
 */
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
  |--------------------------------------------------------------------------
  | Enable Query Strings
  |--------------------------------------------------------------------------
  |
  | By default CodeIgniter uses search-engine friendly segment based URLs:
  | example.com/who/what/where/
  |
  | By default CodeIgniter enables access to the $_GET array.  If for some
  | reason you would like to disable it, set 'allow_get_array' to FALSE.
  |
  | You can optionally enable standard query string based URLs:
  | example.com?who=me&what=something&where=here
  |
  | Options are: TRUE or FALSE (boolean)
  |
  | The other items let you set the query string 'words' that will
  | invoke your controllers and its functions:
  | example.com/index.php?c=controller&m=function
  |
  | Please note that some of the helpers won't work as expected when
  | this feature is enabled, since CodeIgniter is designed primarily to
  | use segment based URLs.
  |
 */
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd'; // experimental not currently in use

/*
  |--------------------------------------------------------------------------
  | Error Logging Threshold
  |--------------------------------------------------------------------------
  |
  | If you have enabled error logging, you can set an error threshold to
  | determine what gets logged. Threshold options are:
  | You can enable error logging by setting a threshold over zero. The
  | threshold determines what gets logged. Threshold options are:
  |
  |	0 = Disables logging, Error logging TURNED OFF
  |	1 = Error Messages (including PHP errors)
  |	2 = Debug Messages
  |	3 = Informational Messages
  |	4 = All Messages
  |
  | For a live site you'll usually only enable Errors (1) to be logged otherwise
  | your log files will fill up very fast.
  |
 */
$config['log_threshold'] = 3;

/*
  |--------------------------------------------------------------------------
  | Error Logging Directory Path
  |--------------------------------------------------------------------------
  |
  | Leave this BLANK unless you would like to set something other than the default
  | application/logs/ folder. Use a full server path with trailing slash.
  |
 */
// test
$config['log_path'] = 'd:/log/codeIgniterAdmin/';
//$config['log_path'] = '';

/*
  |--------------------------------------------------------------------------
  | Date Format for Logs
  |--------------------------------------------------------------------------
  |
  | Each item that is logged has an associated date. You can use PHP date
  | codes to set your own date formatting
  |
 */
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
  |--------------------------------------------------------------------------
  | Cache Directory Path
  |--------------------------------------------------------------------------
  |
  | Leave this BLANK unless you would like to set something other than the default
  | system/cache/ folder.  Use a full server path with trailing slash.
  |
 */
$config['cache_path'] = '';

/*
  |--------------------------------------------------------------------------
  | Encryption Key
  |--------------------------------------------------------------------------
  |
  | If you use the Encryption class or the Session class you
  | MUST set an encryption key.  See the user guide for info.
  |
 */
$config['encryption_key'] = 'ciknoJN';

/*
  |--------------------------------------------------------------------------
  | Session Variables
  |--------------------------------------------------------------------------
  |
  | 'sess_cookie_name'		= the name you want for the cookie
  | 'sess_expiration'			= the number of SECONDS you want the session to last.
  |   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
  | 'sess_expire_on_close'	= Whether to cause the session to expire automatically
  |   when the browser window is closed
  | 'sess_encrypt_cookie'		= Whether to encrypt the cookie
  | 'sess_use_database'		= Whether to save the session data to a database
  | 'sess_table_name'			= The name of the session database table
  | 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
  | 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
  | 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
  |
 */
$config['sess_cookie_name'] = 'smc_sess_';
$config['sess_expiration'] = 7200;
$config['sess_expire_on_close'] = FALSE;
$config['sess_encrypt_cookie'] = FALSE;
$config['sess_use_database'] = FALSE;
$config['sess_table_name'] = FALSE;
$config['sess_match_ip'] = FALSE;
$config['sess_match_useragent'] = TRUE;
$config['sess_time_to_update'] = 300;


$config['proxy_ips'] = '';

/*
 * tencent platform api url
 */
$config['tencent_openapi_url'] = 'http://119.147.19.43';
$config['tencent_openapi_url_safe'] = 'https://119.147.19.43';

$config['game_id_group'] = array(
    '001' => 'texaspoker',
    '002' => 'zjh',
    '003' => 'guandan',
    '004' => 'niuniu',
    '005' => 'fish',
    '006' => 'gdzjh',
    );

$config['groups'] = array(
	'1'		=>	'管理员',
	'2'		=>	'运营人员',
	'3'		=>	'客服人员',
);

$config['dbconfig'] = array(
    //'hostname' => '10.0.0.11',
 //   'hostname' => '211.151.33.246',
    // 'hostname' => '211.151.33.250',
    'hostname' => '10.0.0.40',
    'username' => 'dbuserx',
    'password' => 'dbuserx123',
    'database' => '',
    'dbdriver' => 'mysql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => FALSE,
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'port'     => 2918,
);


/*
$config['hostlist'] = array(
    //'m1' => '10.0.0.11', //major
    //'m2' => '10.0.0.12', //major
    //'b1' => '10.0.0.11', //backup
    //'b2' => '10.0.0.12', //backup
    'm1' => '211.151.33.246', //major
    'm2' => '211.151.33.248', //major
    'b1' => '211.151.33.246', //backup
    'b2' => '211.151.33.248', //backup
);
 * 
 * 
 */

$config['hostlist'] = array(
    //'m1' => '10.0.0.11', //major
    //'m2' => '10.0.0.12', //major
    //'b1' => '10.0.0.11', //backup
    //'b2' => '10.0.0.12', //backup
    'm1' => '10.0.0.30', //major
    'm2' => '10.0.0.30', //major
    'b1' => '10.0.0.40', //backup
    'b2' => '10.0.0.40', //backup
);

$config['hostlist8'] = array(
    'm1' => '10.0.0.29',
    'm2' => '10.0.0.22', 
    'm3' => '10.0.0.23',
    'm4' => '10.0.0.24',  
    'm5' => '10.0.0.25',
    'm6' => '10.0.0.26', 
    'm7' => '10.0.0.27',
    'm8' => '10.0.0.28', 
    
    'b1' => '10.0.0.39',
    'b2' => '10.0.0.32', 
    'b3' => '10.0.0.33',
    'b4' => '10.0.0.34', 
    'b5' => '10.0.0.35',
    'b6' => '10.0.0.36', 
    'b7' => '10.0.0.37',
    'b8' => '10.0.0.38', 
);


// 数据库名和表名
$config['dbalias'] = array(
    // user
    'dbuser'      => 'CASINOUSERDB_',

    'tbuser'      => 'CASINOUSER_',
    'tbuseridx'   => 'CASINOUSER2ACCOUNT_',

    // history
    'dbgamehis'   => 'CASINOGAMEHISDB',
    'tbbroke'     => 'CASINOBROKERAGEHISTORY',        // 抽水
    'tbgift'      => 'CASINOGIFTHISTORY',
    'tbgiftchip'  => 'CASINOGIFTCHIPHISTORY',
    'tbofficegift'=> 'CASINOOFFICIALGIFTHISTORY',
    'tbaddsubhis' => 'CASINOBACKGROUNDADDSUBHISTORY', // 后台加减分
    'tbadwall'    => 'CASINOADWALLHISTORY',           // 广告墙
    'tbloginhis'  => 'CASINOLOGINHISTORY',            // 登录
    'tbgamehis'   => 'CASINOGAMEHISTORY',             // 输赢记录 
    'tbreghis'    => 'CASINOREGISTERHISTORY',         // 注册记录

    // pay
    'dbpay'        => 'CASINOBUYHISDB',
    'tbshenzhoufu' => 'CASINOSHENZHOUFURECORD',
    'tbappstore'   => 'CASINOAPPSTORERECORD',
    'tbweipai'     => 'CASINOWEIPAIRECORD',
    'tbalipay'     => 'CASINOALIPAYRECORD',
    'tbpay91'      => 'CASINOJIUYAORECORD',
    'tbcmb'        => 'CASINOCHINAMOBILERECORD',       // 中国移动
    'tb360'        => 'CASINOSANLIULINGRECORD',        // qihoo360
    'tbcunm'       => 'CASINOCHINAUNICOMRECORD',       // 联通承泰代理   
    'tbwoshop'     => 'CASINOCHINAUNICOMWORECORD',     // 联通沃商城
    'tbyifutong'   => 'CASINOYIFUTONGRECORD',          // 易付通
    'tbtelcardex'  => 'CASINOTELCARDEXCHANGERECORD',  // 兑换礼品记录

    // Global
    'dbglobal'     => 'CASINOGLOBALINFO',
    'tbadwallinfo' => 'CASINOADWALLINFO',
    'tbgameadwall' => 'CASINOGAMEADWALLINFO',
    'tbglobgift'   => 'CASINOGIFT',                   // 礼物表
    'tbbrokerate'  => 'CASINOBROKERAGERATE',          // 抽水率 
    'tbtotalchip'  => 'CASINOTOTALCHIPNUM',           // 总分 
    'tbonlinestat' => 'CASINOTOTALONLINESTATISTICS',  // 在线人数 
    'tbbroadecast' => 'CASINOSYSTEMBROADCAST',        // 系统广播 
    'propertytype' => 'CASINOPROPERTYTYPE', 
    'propertylist' => 'CASINOPROPERTY',
    'gifttype'     => 'CASINOGIFTTYPE',
    'giftlist'     => 'CASINOGIFT',
    'tbmaxid'      => 'CASINOUSERIDGENERATOR',
    'exchangegift' => 'CASINOEXCHANGEGIFT',           // 礼品
    'topchipslist' => 'CASINOTOPCHIPSLIST',           // 排行榜
    'notifycation' => 'CASINONOTIFICATIONINFO',       // 系统公告

    // blacklist
    'dbblacklist'  => 'CASINOBLACKLISTDB',
    'tbblackip'    => 'CASINOIPBLACKLIST', 
    'tbblackmac'   => 'CASINOMACBLACKLIST', 
    'tbblackid'    => 'CASINOUSERIDBLACKLIST', 

);


$config['midlayer'] = array(
    '0' => array(
        'host' => DISPATCH_SERVER_IP,
        'port' => DISPATCH_SERVER_PORT,
    ),
);


/*
  |--------------------------------------------------------------------------
  | Cookie Related Variables
  |--------------------------------------------------------------------------
  |
  | 'cookie_prefix' = Set a prefix if you need to avoid collisions
  | 'cookie_domain' = Set to .your-domain.com for site-wide cookies
  | 'cookie_path'   =  Typically will be a forward slash
  | 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
  |
 */
$config['cookie_prefix'] = "";
$config['cookie_domain'] = "";
$config['cookie_path'] = "/";
$config['cookie_secure'] = FALSE;

/*
  |--------------------------------------------------------------------------
  | Global XSS Filtering
  |--------------------------------------------------------------------------
  |
  | Determines whether the XSS filter is always active when GET, POST or
  | COOKIE data is encountered
  |
 */
$config['global_xss_filtering'] = FALSE;

/*
  |--------------------------------------------------------------------------
  | Cross Site Request Forgery
  |--------------------------------------------------------------------------
  | Enables a CSRF cookie token to be set. When set to TRUE, token will be
  | checked on a submitted form. If you are accepting user data, it is strongly
  | recommended CSRF protection be enabled.
  |
  | 'csrf_token_name' = The token name
  | 'csrf_cookie_name' = The cookie name
  | 'csrf_expire' = The number in seconds the token should expire.
 */
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
  |--------------------------------------------------------------------------
  | Output Compression
  |--------------------------------------------------------------------------
  |
  | Enables Gzip output compression for faster page loads.  When enabled,
  | the output class will test whether your server supports Gzip.
  | Even if it does, however, not all browsers support compression
  | so enable only if you are reasonably sure your visitors can handle it.
  |
  | VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
  | means you are prematurely outputting something to your browser. It could
  | even be a line of whitespace at the end of one of your scripts.  For
  | compression to work, nothing can be sent before the output buffer is called
  | by the output class.  Do not 'echo' any values with compression enabled.
  |
 */
$config['compress_output'] = FALSE;

/*
  |--------------------------------------------------------------------------
  | Master Time Reference
  |--------------------------------------------------------------------------
  |
  | Options are 'local' or 'gmt'.  This pref tells the system whether to use
  | your server's local time as the master 'now' reference, or convert it to
  | GMT.  See the 'date helper' page of the user guide for information
  | regarding date handling.
  |
 */
$config['time_reference'] = 'local';


/*
  |--------------------------------------------------------------------------
  | Rewrite PHP Short Tags
  |--------------------------------------------------------------------------
  |
  | If your PHP installation does not have short tag support enabled CI
  | can rewrite the tags on-the-fly, enabling you to utilize that syntax
  | in your view files.  Options are TRUE or FALSE (boolean)
  |
 */
$config['rewrite_short_tags'] = FALSE;


/*
  |--------------------------------------------------------------------------
  | Reverse Proxy IPs
  |--------------------------------------------------------------------------
  |
  | If your server is behind a reverse proxy, you must whitelist the proxy IP
  | addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
  | header in order to properly identify the visitor's IP address.
  | Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
  |
 */
$config['proxy_ips'] = '';

$config['no_tongji'] = array(
//	49=>'全民玩德扑Ios',
//	1049=>'全民玩德扑Android',
//	54 => '月月电玩城Ios',
//	1054 => '月月电玩城Android'
);

// [170221] xh add: 渠道列表的配置修改
$config['allChannelList'] = array(
	array('channelId' => 1, 'tag' => 'com.liuliugame1.fageqipai1', 'name' => '发哥游戏Ios', 'url' => 'https://itunes.apple.com/cn/app/fa-ge-dou-niu/id1162739140?l=zh&ls=1&mt=8'),
	array('channelId' => 1001, 'tag' => 'com.liuliugame1.fgyx99', 'name' => '发哥游戏Android', 'url' => 'http://www.fageyx.com'),
	array('channelId' => 2, 'tag' => 'com.liuliugame1.kuruiyouxi', 'name' => '酷锐游戏Ios', 'url' => 'https://itunes.apple.com/us/app/ku-rui-bu-yu-jing-dian-dian/id1163223910?l=zh&ls=1&mt=8'),
	array('channelId' => 1002, 'tag' => 'com.liuliugame1.kryx99', 'name' => '酷锐游戏Android', 'url' => 'http://www.ruikuyx.com'),
	array('channelId' => 3, 'tag' => 'com.liuliugame1.zhenzhenyouxi', 'name' => '真真游戏Ios', 'url' => 'https://itunes.apple.com/us/app/zhen-zhen-you-xi/id1163213212?l=zh&ls=1&mt=8'),
	array('channelId' => 4, 'tag' => 'com.liuliugame1.jileyouxi', 'name' => '极乐游戏Ios', 'url' => 'https://itunes.apple.com/cn/app/ji-le-dian-wan-cheng-wan-ren/id1163523179?l=zh&ls=1&mt=8'),
	array('channelId' => 1004, 'tag' => 'com.liuliugame1.jldwc99', 'name' => '极乐游戏Android', 'url' => 'http://www.jileuc.com'),
	array('channelId' => 5, 'tag' => 'com.liuliugame1.vvyouxi', 'name' => 'VV娱乐Ios', 'url' => 'https://itunes.apple.com/cn/app/vv-le-dian-wan-cheng-duo-kuan/id1163528793?l=zh&ls=1&mt=8'),
	array('channelId' => 251, 'tag' => 'com.liuliugame1.vvyule1', 'name' => 'VV娱乐Android', 'url' => 'http://www.vvlqp.com'),
	array('channelId' => 6, 'tag' => 'com.liuliugame1.bubuzhajinhua', 'name' => '布布扎金花Ios', 'url' => 'https://itunes.apple.com/cn/app/bu-bu-zha-jin-hua-zhen-ren/id1161231743?l=zh&ls=1&mt=8'),
	array('channelId' => 1006, 'tag' => 'com.liuliugame1.bbzjh99', 'name' => '布布扎金花Android', 'url' => 'http://www.bubuuc.com'),
	array('channelId' => 7, 'tag' => 'com.liuliugame1.xiahailaojin', 'name' => '下海捞金Ios', 'url' => ''),
	array('channelId' => 8, 'tag' => 'com.liuliugame1.quanmingdepuquan', 'name' => '天天德扑圈Ios', 'url' => 'https://itunes.apple.com/us/app/天天德扑圈-玩德州扑克免费送金币/id1168982421?l=zh&ls=1&mt=8'),
	array('channelId' => 9, 'tag' => 'com.liuliugame1.wwdwc', 'name' => '旺旺电玩城Ios', 'url' => 'https://itunes.apple.com/cn/app/wang-wang-dian-wan-cheng-mei/id1170046674?l=zh&ls=1&mt=8'),
	array('channelId' => 1009, 'tag' => 'com.liuliugame1.wwdwc99', 'name' => '旺旺电玩城Android', 'url' => 'http://www.wangwanguc.com'),
	array('channelId' => 10, 'tag' => 'com.liuliugame1.ycby', 'name' => '异趣捕鱼Ios', 'url' => ''),
	array('channelId' => 11, 'tag' => 'com.liuliugame1.qlddz', 'name' => '奇乐斗地主Ios', 'url' => ''),
	array('channelId' => 12, 'tag' => 'com.liuliugame1.huoliniuniu', 'name' => '火力牛牛Ios', 'url' => 'https://itunes.apple.com/cn/app/huo-li-niu-niu-zhong-guo-zui/id1170553449?l=zh&ls=1&mt=8'),
	array('channelId' => 1012, 'tag' => 'com.liuliugame1.hlnn99', 'name' => '火力牛牛Android', 'url' => 'http://www.hotuc.com'),
	array('channelId' => 13, 'tag' => 'com.liuliugame1.dakayouxi', 'name' => '大咖游戏Ios', 'url' => 'https://itunes.apple.com/cn/app/da-ka-you-xi-zhen-ren-feng/id1172319362?l=zh&ls=1&mt=8'),
	array('channelId' => 1013, 'tag' => 'com.liuliugame1.dkyx99', 'name' => '大咖游戏Android', 'url' => 'http://www.dkayx.com'),
	array('channelId' => 14, 'tag' => 'com.liuliugame1.qiqidoudizhu', 'name' => '奇奇斗地主Ios', 'url' => 'https://itunes.apple.com/us/app/qi-qi-dou-zhu-feng-kuang-zhuan/id1172350833?l=zh&ls=1&mt=8'),
	array('channelId' => 1014, 'tag' => 'com.liuliugame1.jjddz99', 'name' => '奇奇斗地主Android', 'url' => ''),
	array('channelId' => 15, 'tag' => 'com.liuliugame1.ttzjh', 'name' => '天天扎金花Ios', 'url' => 'https://itunes.apple.com/cn/app/tian-tian-zha-jin-hua-quan/id1173310479?l=zh&ls=1&mt=8'),
	array('channelId' => 1015, 'tag' => 'com.liuliugame1.ttzjh99', 'name' => '天天扎金花Android', 'url' => 'http://www.tiantianzjh.com'),
	array('channelId' => 16, 'tag' => 'com.liuliugame1.btddz', 'name' => '博天斗地主Ios', 'url' => ''),
	array('channelId' => 17, 'tag' => 'com.liuliugame1.hhddz', 'name' => '坏坏斗地主Ios', 'url' => ''),
	array('channelId' => 18, 'tag' => 'com.liuliugame1.cjysz', 'name' => '超级赢三张Ios', 'url' => 'https://itunes.apple.com/cn/app/chao-ji-ying-san-zhang-zhen/id1173466471?l=zh&ls=1&mt=8'),
	array('channelId' => 1018, 'tag' => 'com.liuliugame1.cjysz99', 'name' => '超级赢三张Android', 'url' => 'http://www.cjdizhi.com'),
	array('channelId' => 19, 'tag' => 'com.liuliugame1.nnzjh', 'name' => '牛牛诈金花Ios', 'url' => 'https://itunes.apple.com/cn/app/niu-niu-zha-jin-hua-quan-min/id1173811882?l=zh&ls=1&mt=8'),
	array('channelId' => 1019, 'tag' => 'com.liuliugame1.nnzjh99', 'name' => '牛牛诈金花Android', 'url' => 'http://www.niuniupq.com'),
	array('channelId' => 20, 'tag' => 'com.liuliugame1.ftqp', 'name' => '飞天棋牌Ios', 'url' => 'https://itunes.apple.com/us/app/fei-tian-qi-pai-tu-hao-zha/id1174019536?l=zh&ls=1&mt=8'),
	array('channelId' => 1020, 'tag' => 'com.liuliugame1.ftqp99', 'name' => '飞天棋牌Android', 'url' => 'http://www.15feitian.com'),
	array('channelId' => 21, 'tag' => 'com.liuliugame1.bsddz', 'name' => '新土豪炸金花Ios', 'url' => 'https://itunes.apple.com/cn/app/bo-sheng-dou-zhu-zhen-ren/id1174230466?l=zh&ls=1&mt=8'),
	array('channelId' => 1021, 'tag' => 'com.liuliugame1.bsddz99', 'name' => '新土豪炸金花Android', 'url' => 'http://www.91bosheng.com'),
	array('channelId' => 22, 'tag' => 'com.liuliugame1.llzjh', 'name' => '六六扎金花Ios', 'url' => ''),
	array('channelId' => 23, 'tag' => 'com.liuliugame1.ttddz', 'name' => '土豪斗牛牛Ios', 'url' => 'https://itunes.apple.com/cn/app/tao-tao-dou-zhu-quan-min-huan/id1174780367?l=zh&ls=1&mt=8'),
	array('channelId' => 1023, 'tag' => 'com.liuliugame1.ttddz99', 'name' => '土豪斗牛牛Android', 'url' => 'http://www.taotaoddz.com'),
	array('channelId' => 24, 'tag' => 'com.liuliugame1.bzqp', 'name' => '博尊斗牛Ios', 'url' => 'https://itunes.apple.com/cn/app/bo-zun-qi-pai-huan-le-dou/id1174800264?l=zh&ls=1&mt=8'),
	array('channelId' => 1024, 'tag' => 'com.liuliugame1.bzqp99', 'name' => '博尊斗牛Android', 'url' => 'http://www.bozunyx.com'),
	array('channelId' => 25, 'tag' => 'com.liuliugame1.nnzy', 'name' => '牛牛之约Ios', 'url' => 'https://itunes.apple.com/cn/app/niu-niu-zhi-yue-tian-tian/id1175151668?l=zh&ls=1&mt=8'),
	array('channelId' => 1025, 'tag' => 'com.liuliugame1.nnzy99', 'name' => '牛牛之约Android', 'url' => 'http://www.iniuniuyx.com'),
	array('channelId' => 26, 'tag' => 'com.liuliugame1.hlysz', 'name' => '欢乐赢三张Ios', 'url' => 'https://itunes.apple.com/cn/app/huan-le-ying-san-zhang-tian/id1175155431?l=zh&ls=1&mt=8'),
	array('channelId' => 1026, 'tag' => 'com.liuliugame1.hlysz99', 'name' => '欢乐赢三张Android', 'url' => 'http://www.huanleuc.com'),
	array('channelId' => 27, 'tag' => 'com.liuliugame1.tjly', 'name' => '淘金乐园Ios', 'url' => 'https://itunes.apple.com/cn/app/tao-jin-le-yuan-ying-san-zhang/id1175524641?l=zh&ls=1&mt=8'),
	array('channelId' => 276, 'tag' => 'com.liuliugame1.tjly2', 'name' => '淘金乐园Android', 'url' => 'http://www.taojinyx.com'),
	array('channelId' => 28, 'tag' => 'com.liuliugame1.fkzjh', 'name' => '疯狂炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/feng-kuang-zha-jin-hua-zha/id1175722341?l=zh&ls=1&mt=8'),
	array('channelId' => 1028, 'tag' => 'com.liuliugame1.fkzjh99', 'name' => '疯狂炸金花Android', 'url' => 'http://www.fkjinhua.com'),
	array('channelId' => 29, 'tag' => 'com.liuliugame1.ljddz', 'name' => '新土豪斗牛Ios', 'url' => 'https://itunes.apple.com/cn/app/le-jin-dou-zhu-zhen-ren-dou/id1175727744?l=zh&ls=1&mt=8'),
	array('channelId' => 1029, 'tag' => 'com.liuliugame1.ljddz99', 'name' => '新土豪斗牛Android', 'url' => 'http://www.lejinyx.com'),
	array('channelId' => 30, 'tag' => 'com.liuliugame1.thzjh', 'name' => '土豪砸金花Ios', 'url' => 'https://itunes.apple.com/cn/app/tu-hao-za-jin-hua-zhen-ren/id1176005319?l=zh&ls=1&mt=8'),
	array('channelId' => 1030, 'tag' => 'com.liuliugame1.thzjh99', 'name' => '土豪砸金花Android', 'url' => 'http://www.tuhaouc.com'),
	array('channelId' => 31, 'tag' => 'com.liuliugame1.daddz', 'name' => '超级斗牛大亨Ios', 'url' => 'https://itunes.apple.com/us/app/duo-ai-dou-zhu-tian-tian-qi/id1176014589?l=zh&ls=1&mt=8'),
	array('channelId' => 1031, 'tag' => 'com.liuliugame1.daddz99', 'name' => '超级斗牛大亨Android ', 'url' => 'http://www.duoaiyx.com'),
	array('channelId' => 32, 'tag' => 'com.liuliugame1.ywds', 'name' => '欲望都市Ios', 'url' => 'https://itunes.apple.com/us/app/yu-wang-dou-shi-ao-men-tu/id1175985422?l=zh&ls=1&mt=8'),
	array('channelId' => 277, 'tag' => 'com.liuliugame1.ywds2', 'name' => '欲望都市Android', 'url' => 'http://www.yuwangyx.com'),
	array('channelId' => 33, 'tag' => 'com.liuliugame1.kgzjh', 'name' => '首富炸金花Ios ', 'url' => 'https://itunes.apple.com/us/app/ku-ge-zha-jin-hua-zha-jin/id1176355997?l=zh&ls=1&mt=8'),
	array('channelId' => 1033, 'tag' => 'com.liuliugame1.kgzjh99', 'name' => '首富炸金花Android', 'url' => 'http://www.kugeyx.com'),
	array('channelId' => 34, 'tag' => 'com.liuliugame1.lkddz2', 'name' => '天天赚棋牌合集Ios', 'url' => 'https://itunes.apple.com/us/app/le-ke-dou-zhu-tian-tian-qi/id1176365662?l=zh&ls=1&mt=8'),
	array('channelId' => 1034, 'tag' => 'com.liuliugame1.lkddz99', 'name' => '天天赚棋牌合集Android ', 'url' => 'http://www.lekeyx.com'),
	array('channelId' => 35, 'tag' => 'com.liuliugame1.ylddz', 'name' => '天天赚斗牛牛Ios ', 'url' => 'https://itunes.apple.com/us/app/yu-le-dou-zhu-huan-le-jie/id1176368672?l=zh&ls=1&mt=8'),
	array('channelId' => 1035, 'tag' => 'com.liuliugame1.ylddz99', 'name' => '天天赚斗牛牛Android', 'url' => 'http://www.yuleuc.com'),
	array('channelId' => 36, 'tag' => 'com.liuliugame1.qqddz', 'name' => '棋棋斗地主Ios', 'url' => 'https://itunes.apple.com/cn/app/qi-qi-dou-zhu-zhang-shang/id1176782994?l=zh&ls=1&mt=8'),
	array('channelId' => 1036, 'tag' => 'com.liuliugame1.qqddz99', 'name' => '棋棋斗地主Android  ', 'url' => 'http://www.qiqiddz.com'),
	array('channelId' => 37, 'tag' => 'com.liuliugame1.ddzjh', 'name' => '多多炸金花Ios ', 'url' => 'https://itunes.apple.com/us/app/duo-duo-zha-jin-hua-mian-fei/id1176784584?l=zh&ls=1&mt=8'),
	array('channelId' => 1037, 'tag' => 'com.liuliugame1.ddzjh99', 'name' => '多多炸金花Android', 'url' => 'http://www.ddjinhua.com'),
	array('channelId' => 38, 'tag' => 'com.liuliugame1.yybydr', 'name' => '歪歪捕鱼达人Ios', 'url' => ''),
	array('channelId' => 39, 'tag' => 'com.liuliugame1.lxbycq', 'name' => '热血捕鱼传奇Ios', 'url' => ''),
	array('channelId' => 40, 'tag' => 'com.liuliugame1.ffddz', 'name' => '土豪捕鱼达人Ios', 'url' => 'https://itunes.apple.com/us/app/fei-fei-dou-zhu-tu-hao-qi/id1177873740?l=zh&ls=1&mt=8'),
	array('channelId' => 1040, 'tag' => 'com.liuliugame1.ffddz99', 'name' => '土豪捕鱼达人Android', 'url' => 'http://www.feifeiuc.com'),
	array('channelId' => 41, 'tag' => 'com.liuliugame1.jdddz', 'name' => '三张炸金花Ios', 'url' => 'https://itunes.apple.com/cn/app/jing-dian-dou-zhu-mei-nu-qi/id1177889016?l=zh&ls=1&mt=8'),
	array('channelId' => 1041, 'tag' => 'com.liuliugame1.jdddz99', 'name' => '三张炸金花Android', 'url' => 'http://www.jingdianuc.com'),
	array('channelId' => 42, 'tag' => 'com.liuliugame1.byjh', 'name' => '捕鱼金花Ios', 'url' => 'https://itunes.apple.com/cn/app/bu-yu-jin-hua-tu-hao-mei-nu/id1178324931?l=zh&ls=1&mt=8'),
	array('channelId' => 1042, 'tag' => 'com.liuliugame1.byjh99', 'name' => '捕鱼金花Android', 'url' => 'http://www.buyujinhua.com'),
	array('channelId' => 43, 'tag' => 'com.liuliugame1.tyby', 'name' => '天涯捕鱼Ios', 'url' => 'https://itunes.apple.com/cn/app/tian-ya-bu-yu-huan-le-qi-pai/id1178327409?l=zh&ls=1&mt=8'),
	array('channelId' => 1043, 'tag' => 'com.liuliugame1.tyby99', 'name' => '天涯捕鱼Android', 'url' => 'http://www.tianyabuyu.com'),
	array('channelId' => 44, 'tag' => 'com.liuliugame1.zrzjh', 'name' => '真人扎金花Ios', 'url' => 'https://itunes.apple.com/cn/app/zhen-ren-zha-jin-hua-tu-hao/id1178507369?l=zh&ls=1&mt=8'),
	array('channelId' => 1044, 'tag' => 'com.liuliugame1.zrzjh99', 'name' => '真人扎金花Android', 'url' => 'http://www.hotjinhua.com'),
	array('channelId' => 45, 'tag' => 'com.liuliugame1.qmfkddz', 'name' => '全民疯狂斗地主Ios', 'url' => 'https://itunes.apple.com/cn/app/quan-min-feng-kuang-dou-zhu/id1178507847?l=zh&ls=1&mt=8'),
	array('channelId' => 1045, 'tag' => 'com.liuliugame1.qmfkddz99', 'name' => '全民疯狂斗地主Android', 'url' => 'http://www.dizhu666.com'),
	array('channelId' => 46, 'tag' => 'com.liuliugame1.shdj', 'name' => '深海夺金Ios', 'url' => 'https://itunes.apple.com/cn/app/shen-hai-duo-jin-bu-yu-deng/id1178513097?l=zh&ls=1&mt=8'),
	array('channelId' => 1046, 'tag' => 'com.liuliugame1.shdj99', 'name' => '深海夺金Android', 'url' => 'http://www.915buyu.com'),
	array('channelId' => 47, 'tag' => 'com.liuliugame1.nnsj', 'name' => '牛牛世界Ios', 'url' => 'https://itunes.apple.com/cn/app/niu-niu-shi-jie-tu-hao-qi/id1178516927?l=zh&ls=1&mt=8'),
	array('channelId' => 1047, 'tag' => 'com.liuliugame1.nnsj99', 'name' => '牛牛世界Android', 'url' => 'http://www.915niuniu.com'),
	array('channelId' => 48, 'tag' => 'com.liuliugame1.amdp', 'name' => '澳门德扑Ios', 'url' => 'https://itunes.apple.com/cn/app/ao-men-pu-qi-pai-da-he-ji!/id1178902954?l=zh&ls=1&mt=8'),
	array('channelId' => 1048, 'tag' => 'com.liuliugame1.amdp99', 'name' => '澳门德扑Android', 'url' => 'http://www.15aomen.com'),
	array('channelId' => 49, 'tag' => 'com.liuliugame1.qmwdp', 'name' => '全民玩德扑Ios', 'url' => 'https://itunes.apple.com/us/app/quan-min-wan-pu-qi-pai-da/id1178907914?l=zh&ls=1&mt=8'),
	array('channelId' => 1049, 'tag' => 'com.liuliugame1.qmwdp99', 'name' => '全民玩德扑Android', 'url' => 'http://www.quanmingpk.com'),
	array('channelId' => 50, 'tag' => 'com.liuliugame1.hgzjh', 'name' => '豪哥炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/hao-ge-zha-jin-hua-zhen-tu/id1179662608?l=zh&ls=1&mt=8'),
	array('channelId' => 1050, 'tag' => 'com.liuliugame1.hgzjh99', 'name' => '豪哥炸金花Android', 'url' => 'http://www.haogeyx.com'),
	array('channelId' => 51, 'tag' => 'com.liuliugame1.ttzjh2', 'name' => '天天炸金花Ios', 'url' => 'https://itunes.apple.com/cn/app/tian-tian-zha-jin-hua-bai/id1179664652?l=zh&ls=1&mt=8'),
	array('channelId' => 52, 'tag' => 'com.liuliugame1.jdzjh', 'name' => '经典炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/jing-dian-zha-jin-hua-ying/id1179670411?l=zh&ls=1&mt=8'),
	array('channelId' => 248, 'tag' => 'com.liuliugame1.doudizhu1', 'name' => '六六游戏Android审核包', 'url' => ''),
	array('channelId' => 250, 'tag' => 'com.liuliugame1.androidall1', 'name' => '六六游戏Android', 'url' => ''),
	array('channelId' => 261, 'tag' => 'com.liuliugame1.llyx1', 'name' => '六六游戏Android推广包1', 'url' => ''),
	array('channelId' => 262, 'tag' => 'com.liuliugame1.llyx2', 'name' => '六六游戏Android推广包2', 'url' => ''),
	array('channelId' => 263, 'tag' => 'com.liuliugame1.llyx3', 'name' => '六六游戏Android推广包3', 'url' => ''),
	array('channelId' => 264, 'tag' => 'com.liuliugame1.llyx4', 'name' => '六六游戏Android推广包4', 'url' => ''),
	array('channelId' => 265, 'tag' => 'com.liuliugame1.llyx5', 'name' => '六六游戏Android推广包5', 'url' => ''),
	array('channelId' => 266, 'tag' => 'com.liuliugame1.llyx6', 'name' => '六六游戏Android推广包6', 'url' => ''),
	array('channelId' => 267, 'tag' => 'com.liuliugame1.llyx7', 'name' => '六六游戏Android推广包7', 'url' => ''),
	array('channelId' => 268, 'tag' => 'com.liuliugame1.llyx8', 'name' => '六六游戏Android推广包8', 'url' => ''),
	array('channelId' => 269, 'tag' => 'com.liuliugame1.llyx9', 'name' => '六六游戏Android推广包9', 'url' => ''),
	array('channelId' => 270, 'tag' => 'com.liuliugame1.llyx10', 'name' => '六六游戏Android推广包10', 'url' => ''),
	array('channelId' => 271, 'tag' => 'com.liuliugame1.llyx11', 'name' => '六六游戏Android推广包11', 'url' => ''),
	array('channelId' => 272, 'tag' => 'com.liuliugame1.llyx12', 'name' => '六六游戏Android推广包12', 'url' => ''),
	array('channelId' => 273, 'tag' => 'com.liuliugame1.llyx13', 'name' => '六六游戏Android推广包13', 'url' => ''),
	array('channelId' => 274, 'tag' => 'com.liuliugame1.llyx14', 'name' => '六六游戏Android推广包14', 'url' => ''),
	array('channelId' => 275, 'tag' => 'com.liuliugame1.llyx15', 'name' => '六六游戏Android推广包15', 'url' => ''),
	array('channelId' => 53, 'tag' => 'com.liuliugame1.hlddz2', 'name' => '欢乐斗地主Ios', 'url' => 'https://itunes.apple.com/us/app/huan-le-dou-de-zhu-ru-ci-huan-le/id1185269536?l=zh&ls=1&mt=8 '),
	array('channelId' => 1053, 'tag' => 'com.liuliugame1.hlddz299', 'name' => '欢乐斗地主Android', 'url' => 'http://www.911dizhu.com'),
	array('channelId' => 54, 'tag' => 'com.liuliugame1.yydwc2', 'name' => '月月电玩城Ios', 'url' => 'https://itunes.apple.com/us/app/yue-yue-dian-wan-cheng-yue/id1185271906?l=zh&ls=1&mt=8'),
	array('channelId' => 1054, 'tag' => 'com.liuliugame1.yydwc299', 'name' => '月月电玩城Android', 'url' => 'http://www.yueyueuc.com'),
	array('channelId' => 55, 'tag' => 'com.liuliugame1.nndwc', 'name' => '牛牛电玩城Ios', 'url' => 'https://itunes.apple.com/us/app/niu-niu-dian-wan-cheng-yue/id1185275467?l=zh&ls=1&mt=8'),
	array('channelId' => 1055, 'tag' => 'com.liuliugame1.nndwc99', 'name' => '牛牛电玩城Android', 'url' => 'http://www.niuniudwc.com'),
	array('channelId' => 56, 'tag' => 'com.liuliugame1.hlqps', 'name' => '欢乐棋牌室Ios', 'url' => 'https://itunes.apple.com/us/app/huan-le-qi-pai-shi-tian-tian/id1185277299?l=zh&ls=1&mt=8'),
	array('channelId' => 1056, 'tag' => 'com.liuliugame1.hlqps99', 'name' => '欢乐棋牌室Android', 'url' => 'http://www.huanleqp.com'),
	array('channelId' => 57, 'tag' => 'com.liuliugame1.hldnn', 'name' => '欢乐斗牛牛Ios', 'url' => 'https://itunes.apple.com/us/app/huan-le-dou-niu-niu-chao-ji/id1185278025?l=zh&ls=1&mt=8'),
	array('channelId' => 1057, 'tag' => 'com.liuliugame1.hldnn99', 'name' => '欢乐斗牛牛Android', 'url' => 'http://www.915nn.com'),
	array('channelId' => 58, 'tag' => 'com.liuliugame1.qmdnn', 'name' => '全民斗牛牛Ios', 'url' => 'https://itunes.apple.com/us/app/quan-min-dou-niu-niu-quan/id1185279070?l=zh&ls=1&mt=8'),
	array('channelId' => 1058, 'tag' => 'com.liuliugame1.qmdnn99', 'name' => '全民斗牛牛Android', 'url' => 'http://www.qmniuniu.com'),
	array('channelId' => 59, 'tag' => 'com.liuliugame1.blddz', 'name' => '博乐斗地主Ios', 'url' => 'https://itunes.apple.com/us/app/bo-le-dou-zhu-qing-song-zuo/id1185708537?l=zh&ls=1&mt=8'),
	array('channelId' => 1059, 'tag' => 'com.liuliugame1.blddz99', 'name' => '博乐斗地主Android', 'url' => 'http://www.boleuc.com'),
	array('channelId' => 60, 'tag' => 'com.liuliugame1.jdddz2', 'name' => '经典斗地主2Ios', 'url' => 'https://itunes.apple.com/cn/app/jing-dian-dou-zhu-zui-jing/id1185711473?l=zh&ls=1&mt=8'),
	array('channelId' => 1060, 'tag' => 'com.liuliugame1.jdddz299', 'name' => '经典斗地主2Android', 'url' => 'http://www.dizhu520.com'),
	array('channelId' => 61, 'tag' => 'com.liuliugame1.txqp', 'name' => '天行棋牌Ios', 'url' => 'https://itunes.apple.com/us/app/tian-xing-qi-pai-zhen-ren-you-xi/id1186129793?l=zh&ls=1&mt=8'),
	array('channelId' => 1061, 'tag' => 'com.liuliugame1.txqp99', 'name' => '天行棋牌Android', 'url' => 'http://www.txqpyx.com'),
	array('channelId' => 62, 'tag' => 'com.liuliugame1.mlqp', 'name' => '萌乐棋牌Ios', 'url' => 'https://itunes.apple.com/cn/app/meng-le-qi-pai/id1186132207?l=zh&ls=1&mt=8'),
	array('channelId' => 1062, 'tag' => 'com.liuliugame1.mlqp99', 'name' => '萌乐棋牌Android', 'url' => ''),
	array('channelId' => 63, 'tag' => 'com.liuliugame1.bbzjh2', 'name' => '波波炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/bo-bo-zha-jin-hua/id1186601088?l=zh&ls=1&mt=8'),
	array('channelId' => 1063, 'tag' => 'com.liuliugame1.bbzjh299', 'name' => '波波炸金花Android', 'url' => ''),
	array('channelId' => 64, 'tag' => 'com.liuliugame1.kfysz2', 'name' => '疯狂赢三张Ios', 'url' => ''),
	array('channelId' => 1064, 'tag' => 'com.liuliugame1.kfysz299', 'name' => '疯狂赢三张Android', 'url' => ''),
	array('channelId' => 65, 'tag' => 'com.liuliugame1.ddddz', 'name' => '斗斗斗地主Ios', 'url' => ''),
	array('channelId' => 1065, 'tag' => 'com.liuliugame1.ddddz99', 'name' => '斗斗斗地主Android', 'url' => ''),
	array('channelId' => 66, 'tag' => 'com.liuliugame1.jhddz2', 'name' => '金花斗地主Ios', 'url' => 'https://itunes.apple.com/us/app/jin-hua-dou-de-zhu/id1187058837?l=zh&ls=1&mt=8'),
	array('channelId' => 1066, 'tag' => 'com.liuliugame1.jhddz299', 'name' => '金花斗地主Android', 'url' => 'http://www.jhddz66.com'),
	array('channelId' => 67, 'tag' => 'com.liuliugame1.dpzw', 'name' => '德扑之王Ios', 'url' => 'https://itunes.apple.com/us/app/de-pu-zhi-wang-2017/id1187514668?l=zh&ls=1&mt=8'),
	array('channelId' => 1067, 'tag' => 'com.liuliugame1.dpzw99', 'name' => '德扑之王Android', 'url' => 'http://www.depuyx.com'),
	array('channelId' => 68, 'tag' => 'com.liuliugame1.dwqpc', 'name' => '电玩棋牌城Ios', 'url' => 'https://itunes.apple.com/us/app/dian-wan-qi-pai-cheng/id1187521130?l=zh&ls=1&mt=8'),
	array('channelId' => 1068, 'tag' => 'com.liuliugame1.dwqpc99', 'name' => '电玩棋牌城Android', 'url' => ''),
	array('channelId' => 69, 'tag' => 'com.liuliugame1.mmddz', 'name' => '毛毛斗地主Ios', 'url' => 'https://itunes.apple.com/us/app/mao-mao-dou-zhu-da-jia-yi/id1187660120?l=zh&ls=1&mt=8'),
	array('channelId' => 1069, 'tag' => 'com.liuliugame1.mmddz99', 'name' => '毛毛斗地主Android', 'url' => 'http://www.maomaoddz.com'),
	array('channelId' => 70, 'tag' => 'com.liuliugame1.hldns', 'name' => '欢乐斗牛士Ios', 'url' => ''),
	array('channelId' => 1070, 'tag' => 'com.liuliugame1.hldns99', 'name' => '欢乐斗牛士Android', 'url' => ''),
	array('channelId' => 71, 'tag' => 'com.liuliugame1.ddzjh2', 'name' => '嘟嘟炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/du-du-zha-jin-hua-zhen-ren/id1189802409?l=zh&ls=1&mt=8'),
	array('channelId' => 1071, 'tag' => 'com.liuliugame1.ddzjh299', 'name' => '嘟嘟炸金花Android', 'url' => ''),
	array('channelId' => 72, 'tag' => 'com.liuliugame1.klysz', 'name' => '快乐赢三张Ios', 'url' => 'https://itunes.apple.com/us/app/kuai-le-ying-san-zhang-mei/id1189827309?l=zh&ls=1&mt=8'),
	array('channelId' => 1072, 'tag' => 'com.liuliugame1.klysz99', 'name' => '快乐赢三张Android', 'url' => 'http://www.happyyx.com'),
	array('channelId' => 73, 'tag' => 'com.liuliugame1.dpsj', 'name' => '德扑世界Ios', 'url' => ''),
	array('channelId' => 1073, 'tag' => 'com.liuliugame1.dpsj99', 'name' => '德扑世界Android', 'url' => ''),
	array('channelId' => 74, 'tag' => 'com.liuliugame1.sjdwc', 'name' => '世伽电玩城Ios', 'url' => ''),
	array('channelId' => 1074, 'tag' => 'com.liuliugame1.sjdwc99', 'name' => '世伽电玩城Android', 'url' => ''),
	array('channelId' => 76, 'tag' => 'com.liuliugame1.yhzjh', 'name' => '义豪炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/yi-hao-zha-jin-hua/id1190585449?l=zh&ls=1&mt=8'),
	array('channelId' => 1076, 'tag' => 'com.liuliugame1.yhzjh99', 'name' => '义豪炸金花Android', 'url' => ''),
	array('channelId' => 77, 'tag' => 'com.liuliugame1.qydwc', 'name' => '奇遇电玩城Ios', 'url' => ''),
	array('channelId' => 1077, 'tag' => 'com.liuliugame1.qydwc99', 'name' => '奇遇电玩城Android', 'url' => ''),
	array('channelId' => 79, 'tag' => 'com.liuliugame1.bywww', 'name' => '捕鱼旺旺旺Ios', 'url' => ''),
	array('channelId' => 1079, 'tag' => 'com.liuliugame1.bywww99', 'name' => '捕鱼旺旺旺Android', 'url' => ''),
	array('channelId' => 80, 'tag' => 'com.liuliugame1.wyzjh', 'name' => '我要扎金花Ios', 'url' => 'https://itunes.apple.com/us/app/wo-yao-zha-jin-hua/id1191059846?l=zh&ls=1&mt=8'),
	array('channelId' => 1080, 'tag' => 'com.liuliugame1.wyzjh99', 'name' => '我要扎金花Android', 'url' => ''),
	array('channelId' => 81, 'tag' => 'com.liuliugame1.lldwc', 'name' => '乐乐电玩城Ios', 'url' => 'https://itunes.apple.com/us/app/le-le-dian-wan-cheng/id1191062885?l=zh&ls=1&mt=8'),
	array('channelId' => 1081, 'tag' => 'com.liuliugame1.lldwc99', 'name' => '乐乐电玩城Android', 'url' => ''),
	array('channelId' => 82, 'tag' => 'com.liuliugame1.ttddz1', 'name' => '天天斗地主Ios', 'url' => 'https://itunes.apple.com/us/app/tian-tian-dou-zhu-tu-hao-dou/id1204728602?l=zh&ls=1&mt=8'),
	array('channelId' => 1082, 'tag' => 'com.liuliugame1.ttddz199', 'name' => '天天斗地主Android', 'url' => ''),
	array('channelId' => 1083, 'tag' => 'com.liuliugame1.pjdwc99', 'name' => '葡金电玩城Android', 'url' => ''),
	array('channelId' => 84, 'tag' => 'com.liuliugame1.jhby', 'name' => '江湖捕鱼Ios', 'url' => 'https://itunes.apple.com/us/app/江湖捕鱼/id1208394604?l=zh&ls=1&mt=8'),
	array('channelId' => 1084, 'tag' => 'com.liuliugame1.jhby99', 'name' => '江湖捕鱼Android', 'url' => ''),
	array('channelId' => 1085, 'tag' => 'com.liuliugame1.blddz199', 'name' => '博乐斗地主1Android', 'url' => ''),
	array('channelId' => 1086, 'tag' => 'com.liuliugame1.nnzz99', 'name' => '牛牛之战Android', 'url' => ''),
	array('channelId' => 87, 'tag' => 'com.liuliugame1.kaby', 'name' => '酷爱捕鱼Ios', 'url' => 'https://itunes.apple.com/us/app/江湖捕鱼/id1208394604?l=zh&ls=1&mt=8'),
	array('channelId' => 1087, 'tag' => 'com.liuliugame1.kaby99', 'name' => '酷爱捕鱼Android', 'url' => ''),
	array('channelId' => 88, 'tag' => 'com.liuliugame1.sqzjh', 'name' => '神奇炸金花Ios', 'url' => 'https://itunes.apple.com/us/app/神奇炸金花/id1208458451?l=zh&ls=1&mt=8'),
	array('channelId' => 1088, 'tag' => 'com.liuliugame1.sqzjh99', 'name' => '神奇炸金花Android', 'url' => ''),
	array('channelId' => 89, 'tag' => 'com.jl.2029', 'name' => '风云棋牌Ios', 'url' => ''),
	array('channelId' => 1089, 'tag' => 'com.liuliugame1.fyqp99', 'name' => '风云棋牌Android', 'url' => ''),
	array('channelId' => 1999, 'tag' => 'com.liuliugame1.allgame', 'name' => '棋牌游戏Ios', 'url' => ''),
	array('channelId' => 11001, 'tag' => 'com.liuliugame1.fmyx99', 'name' => '发妹游戏Android', 'url' => ''),
	array('channelId' => 10002, 'tag' => 'com.igame.krby', 'name' => '锐酷游戏iOS', 'url' => ''),
	array('channelId' => 11002, 'tag' => 'com.liuliugame1.rkyx99', 'name' => '锐酷游戏Android', 'url' => ''),
	array('channelId' => 11004, 'tag' => 'com.liuliugame1.jlyx299', 'name' => '及乐游戏Android', 'url' => ''),
	array('channelId' => 11006, 'tag' => 'com.liuliugame1.bbwjh99', 'name' => '布布玩金花Android', 'url' => ''),
	array('channelId' => 10012, 'tag' => 'com.igame.hlnn', 'name' => '活力牛牛iOS', 'url' => ''),
	array('channelId' => 11012, 'tag' => 'com.liuliugame1.hlnn599', 'name' => '活力牛牛Android', 'url' => ''),
	array('channelId' => 11013, 'tag' => 'com.liuliugame1.djyx599', 'name' => '达咖游戏Android', 'url' => ''),
	array('channelId' => 11018, 'tag' => 'com.liuliugame1.cjwjh99', 'name' => '超级玩金花Android', 'url' => ''),
	array('channelId' => 11019, 'tag' => 'com.liuliugame1.nnwjh99', 'name' => '牛牛玩金花Android', 'url' => ''),
	array('channelId' => 11020, 'tag' => 'com.liuliugame1.ftyx99', 'name' => '飞天游戏Android', 'url' => ''),
	array('channelId' => 11029, 'tag' => 'com.liuliugame1.xyhjn99 ', 'name' => '新土豪斗牛Android', 'url' => ''),
	array('channelId' => 11030, 'tag' => 'com.liuliugame1.thwjh99', 'name' => '土豪玩金花Android', 'url' => ''),
	array('channelId' => 11031, 'tag' => 'com.liuliugame1.cjjndh99', 'name' => '超级金牛大亨Android', 'url' => ''),
	array('channelId' => 11032, 'tag' => 'com.liuliugame1.ywcs99', 'name' => '欲望城市Android', 'url' => ''),
	array('channelId' => 11042, 'tag' => 'com.liuliugame1.jhby499', 'name' => '金花捕鱼Android', 'url' => ''),
	array('channelId' => 11043, 'tag' => 'com.liuliugame1.hjby99', 'name' => '海角捕鱼Android', 'url' => ''),
	array('channelId' => 11044, 'tag' => 'com.liuliugame1.zrwjh99', 'name' => '真人玩金花Android', 'url' => ''),
	array('channelId' => 11045, 'tag' => 'com.liuliugame1.qmfkwdz99', 'name' => '全民疯狂玩地主Android', 'url' => ''),
	array('channelId' => 11047, 'tag' => 'com.liuliugame1.jnsj99', 'name' => '金牛世界Android', 'url' => ''),
	array('channelId' => 10048, 'tag' => 'com.igame.amdp', 'name' => '港澳德扑iOS', 'url' => ''),
	array('channelId' => 10148, 'tag' => 'com.liuliugame1.gadp99', 'name' => '港澳德扑Android', 'url' => ''),
	array('channelId' => 11050, 'tag' => 'com.liuliugame1.hgwjh99', 'name' => '豪哥玩金花Android', 'url' => ''),
	array('channelId' => 11060, 'tag' => 'com.liuliugame1.klddz399', 'name' => '快乐斗地主Android', 'url' => ''),
	array('channelId' => 11080, 'tag' => 'com.liuliugame1.wywjh99', 'name' => '我要玩金花Android', 'url' => ''),
	array('channelId' => 10101, 'tag' => 'com.igame.run', 'name' => '大熊田径iOS', 'url' => ''),
	array('channelId' => 20002, 'tag' => 'com.igame.hhddz', 'name' => '辉辉斗地主iOS', 'url' => ''),
	array('channelId' => 21002, 'tag' => 'com.liuliugame1.hhddz99', 'name' => '辉辉斗地主Android', 'url' => ''),
	array('channelId' => 20003, 'tag' => 'com.igame.fmzjh', 'name' => '肥猫扎金花iOS', 'url' => ''),
	array('channelId' => 21003, 'tag' => 'com.liuliugame1.fmzjh99', 'name' => '肥猫扎金花Android', 'url' => ''),
	array('channelId' => 20007, 'tag' => 'com.igame.lsnn', 'name' => '拉斯牛牛iOS', 'url' => ''),
	array('channelId' => 21007, 'tag' => 'com.liuliugame1.lsnn99', 'name' => '拉斯牛牛Android', 'url' => ''),
	array('channelId' => 20015, 'tag' => 'com.igame.clzjh', 'name' => '超利扎金花iOS', 'url' => ''),
	array('channelId' => 21015, 'tag' => 'com.liuliugame1.clzjh99', 'name' => '超利扎金花Android', 'url' => ''),
	array('channelId' => 20016, 'tag' => 'com.igame.xbyddz', 'name' => '西班牙斗地主iOS', 'url' => ''),
	array('channelId' => 21016, 'tag' => 'com.liuliugame1.xbyddz99', 'name' => '西班牙斗地主Android', 'url' => ''),
	array('channelId' => 20017, 'tag' => 'com.igame.hfddz', 'name' => '汇发斗地主iOS', 'url' => ''),
	array('channelId' => 21017, 'tag' => 'com.liuliugame1.hfddz99', 'name' => '汇发斗地主Android', 'url' => ''),
	array('channelId' => 20018, 'tag' => 'com.igame.dhdw', 'name' => '大亨电玩iOS', 'url' => ''),
	array('channelId' => 21018, 'tag' => 'com.liuliugame1.dhdw99', 'name' => '大亨电玩Android', 'url' => ''),
	array('channelId' => 20020, 'tag' => 'com.igame.xsdwc', 'name' => '相思电玩城iOS', 'url' => ''),
	array('channelId' => 21020, 'tag' => 'com.liuliugame1.xsdwc99', 'name' => '相思电玩城Android', 'url' => ''),
	array('channelId' => 20021, 'tag' => 'com.igame.byxsj', 'name' => '捕鱼小司机iOS', 'url' => ''),
	array('channelId' => 21021, 'tag' => 'com.liuliugame1.byxsj99', 'name' => '捕鱼小司机Android', 'url' => ''),
	array('channelId' => 210021, 'tag' => 'com.liuliugame1.byxsj199', 'name' => '捕鱼小司机Android2', 'url' => ''),
	array('channelId' => 20022, 'tag' => 'com.igame.nncs', 'name' => '牛牛传说iOS', 'url' => ''),
	array('channelId' => 21022, 'tag' => 'com.liuliugame1.nncs99', 'name' => '牛牛传说Android', 'url' => ''),
	array('channelId' => 20023, 'tag' => 'com.igame.fkyzjh', 'name' => '疯狂赢炸金花iOS', 'url' => ''),
	array('channelId' => 21023, 'tag' => 'com.liuliugame1..fkyzjh99', 'name' => '疯狂赢炸金花Android', 'url' => ''),
	array('channelId' => 20024, 'tag' => 'com.igame.nnddz', 'name' => '牛牛斗地主iOS', 'url' => ''),
	array('channelId' => 21024, 'tag' => 'com.liuliugame1.nnddz99', 'name' => '牛牛斗地主Android', 'url' => ''),
	array('channelId' => 20025, 'tag' => 'com.igame.fkddnn', 'name' => '疯狂的斗牛牛iOS', 'url' => ''),
	array('channelId' => 21025, 'tag' => 'com.liuliugame1.fkddnn99', 'name' => '疯狂的斗牛牛Android', 'url' => ''),
	array('channelId' => 20026, 'tag' => 'com.igame.ddzcq', 'name' => '斗地主传奇iOS', 'url' => ''),
	array('channelId' => 21026, 'tag' => 'com.liuliugame1.ddzcq99', 'name' => '斗地主传奇Android', 'url' => ''),
	array('channelId' => 20027, 'tag' => 'com.igame.qmhbzjh', 'name' => '全民火爆炸金花iOS', 'url' => ''),
	array('channelId' => 21027, 'tag' => 'com.liuliugame1.qmhbzjh99', 'name' => '全民火爆炸金花Android', 'url' => ''),
	array('channelId' => 20028, 'tag' => 'com.igame.nndmx', 'name' => '牛牛大冒险iOS', 'url' => ''),
	array('channelId' => 21028, 'tag' => 'com.liuliugame1.nndmx99', 'name' => '牛牛大冒险Android', 'url' => ''),
	array('channelId' => 20029, 'tag' => 'com.igame.nndr', 'name' => '牛牛达人iOS', 'url' => ''),
	array('channelId' => 21029, 'tag' => 'com.liuliugame1.nndr99', 'name' => '牛牛达人Android', 'url' => ''),
	array('channelId' => 20030, 'tag' => 'com.igame.zgjh', 'name' => '炸个金花iOS', 'url' => ''),
	array('channelId' => 21030, 'tag' => 'com.liuliugame1.zgjh99', 'name' => '炸个金花Android', 'url' => ''),
	array('channelId' => 20036, 'tag' => 'com.igame.wcddz', 'name' => '旺财斗地主iOS', 'url' => ''),
	array('channelId' => 21036, 'tag' => 'com.liuliugame1.wcddz99', 'name' => '旺财斗地主Android', 'url' => ''),
	array('channelId' => 20037, 'tag' => 'com.igame.cxzjh', 'name' => '诚信炸金花iOS', 'url' => ''),
	array('channelId' => 21037, 'tag' => 'com.liuliugame1.cxzjh99', 'name' => '诚信炸金花Android', 'url' => ''),
	array('channelId' => 20043, 'tag' => 'com.igame.lhdz', 'name' => '利豪德州iOS', 'url' => ''),
	array('channelId' => 21043, 'tag' => 'com.liuliugame1.lhdz99', 'name' => '利豪德州Android', 'url' => ''),
	array('channelId' => 20044, 'tag' => 'com.igame.xsdz', 'name' => '兴盛德州iOS', 'url' => ''),
	array('channelId' => 21044, 'tag' => 'com.liuliugame1.xsdz99', 'name' => '兴盛德州Android', 'url' => ''),
	array('channelId' => 20045, 'tag' => 'com.igame.lgdz', 'name' => '乐高德州iOS', 'url' => ''),
	array('channelId' => 21045, 'tag' => 'com.liuliugame1.lgdz99', 'name' => '乐高德州Android', 'url' => ''),
	array('channelId' => 20047, 'tag' => 'com.igame.ylddz', 'name' => '赢乐斗地主iOS', 'url' => ''),
	array('channelId' => 20048, 'tag' => 'com.igame.xsddz', 'name' => '兴盛斗地主iOS', 'url' => ''),//不要后台看到
	array('channelId' => 21048, 'tag' => 'com.liuliugame1.xsddz99', 'name' => '兴盛斗地主Android', 'url' => ''),//不要后台看到
	array('channelId' => 20049, 'tag' => 'com.igame.newxsddz', 'name' => '新兴盛斗地主iOS', 'url' => ''),
	array('channelId' => 21049, 'tag' => 'com.liuliugame1.newxsddz', 'name' => '新兴盛斗地主Android', 'url' => ''),
	array('channelId' => 20050, 'tag' => 'com.igame.hahddz', 'name' => '华辉斗地主iOS', 'url' => ''),
	array('channelId' => 21050, 'tag' => 'com.liuliugame1.hahddz99', 'name' => '华辉斗地主Android', 'url' => ''),
	array('channelId' => 20051, 'tag' => 'com.igame.xxzjh', 'name' => '晓希炸金花iOS', 'url' => ''),
	array('channelId' => 21051, 'tag' => 'com.liuliugame1.xxzjh99', 'name' => '晓希炸金花Android', 'url' => ''),
	array('channelId' => 20052, 'tag' => 'com.igame.qsdwc', 'name' => '强盛电玩城iOS', 'url' => ''),
	array('channelId' => 21052, 'tag' => 'com.liuliugame1.qsdwc99', 'name' => '强盛电玩城Android', 'url' => ''),
	array('channelId' => 20057, 'tag' => 'com.igame.wzdnn', 'name' => '王者斗牛牛iOS', 'url' => ''),
	array('channelId' => 21057, 'tag' => 'com.liuliugame1.wzdnn99', 'name' => '王者斗牛牛Android', 'url' => ''),
	array('channelId' => 20061, 'tag' => 'com.igame.ggzjh', 'name' => '瓜瓜诈金花iOS', 'url' => ''),
	array('channelId' => 21061, 'tag' => 'com.liuliugame1.ggzjh99', 'name' => '瓜瓜诈金花Android', 'url' => ''),
	array('channelId' => 20092, 'tag' => 'com.igame.xjddz', 'name' => '香金斗地主iOS', 'url' => ''),
	array('channelId' => 20094, 'tag' => 'com.igame.bbldn', 'name' => '宝宝来斗牛iOS', 'url' => ''),
	array('channelId' => 20135, 'tag' => 'com.fishking.base', 'name' => '捕鱼王-再战传说iOS', 'url' => ''),
	array('channelId' => 20137, 'tag' => 'com.fishking3.base', 'name' => 'FishMasteriOS', 'url' => ''),
	array('channelId' => 200001, 'tag' => 'com.game88.zyqp', 'name' => '众娱棋牌iOS', 'url' => ''),
	array('channelId' => 91001, 'tag' => 'com.liuliugame1.ppzjh99', 'name' => '胖胖炸金花Android', 'url' => ''),
	array('channelId' => 91002, 'tag' => 'com.liuliugame1.wzddz99', 'name' => '王者斗地主Android', 'url' => ''),
	array('channelId' => 91003, 'tag' => 'com.liuliugame1.bgdwc99', 'name' => '八哥电玩城Android', 'url' => ''),
	array('channelId' => 91004, 'tag' => 'com.liuliugame1.ftby99', 'name' => '飞天捕鱼Android', 'url' => ''),
	array('channelId' => 91005, 'tag' => 'com.liuliugame1.ggddz99', 'name' => '瓜瓜斗地主Android', 'url' => ''),
	array('channelId' => 91006, 'tag' => 'com.liuliugame1.hsdnn99', 'name' => '超级斗牛大亨2Android', 'url' => ''),
	array('channelId' => 91007, 'tag' => 'com.liuliugame1.fkdjn99', 'name' => '疯狂的金牛Android', 'url' => ''),
	array('channelId' => 91008, 'tag' => 'com.liuliugame1.xddaby99', 'name' => '小多多爱捕鱼Android', 'url' => ''),
	array('channelId' => 91009, 'tag' => 'com.liuliugame1.wyddz99', 'name' => '我要斗地主Android', 'url' => ''),
	array('channelId' => 91010, 'tag' => 'com.liuliugame1.kxysz99', 'name' => '开心赢三张Android', 'url' => ''),
	array('channelId' => 91011, 'tag' => 'com.liuliugame1.fmddz99', 'name' => '肥猫斗地主Android', 'url' => ''),
	array('channelId' => 91012, 'tag' => 'com.liuliugame1.wwby99', 'name' => '旺旺捕鱼Android', 'url' => ''),
	array('channelId' => 91013, 'tag' => 'com.liuliugame1.fhylc99', 'name' => '富豪娱乐城Android', 'url' => ''),
	array('channelId' => 91014, 'tag' => 'com.liuliugame1.dwdfw99', 'name' => '电玩大富翁Android', 'url' => ''),
	array('channelId' => 91016, 'tag' => 'com.liuliugame1.dcddz99', 'name' => '东城斗地主Android', 'url' => ''),
	array('channelId' => 91017, 'tag' => 'com.liuliugame1.fsdnn99', 'name' => '佛山斗牛牛Android', 'url' => ''),
	array('channelId' => 91018, 'tag' => 'com.liuliugame1.alsysz99', 'name' => '爱丽丝赢三张Android', 'url' => ''),
	array('channelId' => 91019, 'tag' => 'com.liuliugame1.dhby99', 'name' => '大话捕鱼Android', 'url' => ''),
	array('channelId' => 91020, 'tag' => 'com.liuliugame1.ttadn99', 'name' => '天天爱斗牛Android', 'url' => ''),	
	array('channelId' => 91021, 'tag' => 'com.liuliugame1.bwddz99', 'name' => '霸王斗地主Android', 'url' => ''),
	array('channelId' => 91022, 'tag' => 'com.liuliugame1.tbysz99', 'name' => '台北赢三张Android', 'url' => ''),	
	array('channelId' => 91023, 'tag' => 'com.liuliugame1.wdzjh99', 'name' => '无敌诈金花Android', 'url' => ''),
	array('channelId' => 91024, 'tag' => 'com.liuliugame1.bypp99', 'name' => '捕鱼泡泡Android', 'url' => ''),
	array('channelId' => 100000, 'tag' => 'com.liuliugame1.new_test', 'name' => '测试用', 'url' => ''),
	array('channelId' => 100001, 'tag' => 'com.newliuliu.bydr', 'name' => '测试支付用iOS', 'url' => ''),
	array('channelId' => 3000, 'tag' => 'com.igame.pacs', 'name' => '平安测试iOS', 'url' => ''),
	array('channelId' => 3001, 'tag' => 'com.liuliugame1.pacs99', 'name' => '平安测试Android', 'url' => ''),
	array('channelId' => 3002, 'tag' => 'com.igame.mlcs', 'name' => '马来牛牛测试iOS', 'url' => ''),
	array('channelId' => 3003, 'tag' => 'com.liuliugame1.mlcs99', 'name' => '马来牛牛测试Android', 'url' => ''),
	array('channelId' => 3004, 'tag' => 'com.igame.dwcs', 'name' => '66对外测试包iOS', 'url' => ''),
	array('channelId' => 3005, 'tag' => 'com.liuliugame1.dwcs99', 'name' => '66对外测试包Android', 'url' => ''),
	array('channelId' => 310001, 'tag' => 'com.liuliugame1.huoxing', 'name' => '火星棋牌Android', 'url' => ''),
	array('channelId' => 310021, 'tag' => 'com.liuliugame1.qnddz99', 'name' => '全能斗地主Android', 'url' => ''),
	array('channelId' => 310022, 'tag' => 'com.game88.wpddz', 'name' => '全能斗地主iOS', 'url' => ''),
	array('channelId' => 310023, 'tag' => 'com.liuliugame1.ylqp', 'name' => '赢乐棋牌iOS', 'url' => ''),
	array('channelId' => 91025, 'tag' => 'com.liuliugame1.xddzjh99', 'name' => '小多多诈金花Android', 'url' => ''),
	array('channelId' => 91026, 'tag' => 'com.liuliugame1.csddz99', 'name' => '财神斗地主Android', 'url' => ''),
	array('channelId' => 91032, 'tag' => 'com.liuliugame1.bydwc99', 'name' => '捕鱼电玩城Android', 'url' => ''),
	array('channelId' => 91033, 'tag' => 'com.liuliugame1.hlysz199', 'name' => '火力赢三张Android', 'url' => ''),
	array('channelId' => 91034, 'tag' => 'com.liuliugame1.fnddz99', 'name' => '肥妞斗地主Android', 'url' => ''),
	array('channelId' => 91035, 'tag' => 'com.liuliugame1.sgjdwc99', 'name' => '水果机电玩城Android', 'url' => ''),
	array('channelId' => 91036, 'tag' => 'com.liuliugame1.dazjh99', 'name' => '独爱诈金花Android', 'url' => ''),
	array('channelId' => 91037, 'tag' => 'com.liuliugame1.kxyc99', 'name' => '开心渔场Android', 'url' => ''),
	array('channelId' => 91038, 'tag' => 'com.liuliugame1.bycq99', 'name' => '捕鱼传奇Android', 'url' => ''),
	array('channelId' => 91039, 'tag' => 'com.liuliugame1.qqby99', 'name' => '琪琪捕鱼Android', 'url' => ''),
	array('channelId' => 21135, 'tag' => 'com.fishking.base99', 'name' => '捕鱼王-再战传说Android', 'url' => ''),
	array('channelId' => 21140, 'tag' => 'com.fishking3.base99', 'name' => 'FishMaster Android', 'url' => ''),
	array('channelId' => 91040, 'tag' => 'com.liuliugame1.fcadn99', 'name' => '非常爱斗牛Android', 'url' => ''),
	array('channelId' => 91041, 'tag' => 'com.liuliugame1.qlyc99', 'name' => '奇乐渔场Android', 'url' => ''),
	array('channelId' => 91042, 'tag' => 'com.liuliugame1.hhddz599', 'name' => '哈哈斗地主Android', 'url' => ''),
	array('channelId' => 91043, 'tag' => 'com.liuliugame1.ftysz99', 'name' => '飞天赢三张Android', 'url' => ''),
	array('channelId' => 91044, 'tag' => 'com.liuliugame1.njby99', 'name' => '农家捕鱼Android', 'url' => ''),
	array('channelId' => 91045, 'tag' => 'com.liuliugame1.ltnn99', 'name' => '乐天牛牛Android', 'url' => ''),
	array('channelId' => 9999, 'tag' => 'com.test.test9999', 'name' => '测试渠道9999', 'url' => ''),
	array('channelId' => 888888, 'tag' => 'com.test.test888888', 'name' => '未知渠道888888', 'url' => ''),
	array('channelId' => 510001, 'tag' => 'com.liuliugame1.h5', 'name' => '溜溜H5测试', 'url' => ''),
);

// 生成渠道列表的方法
if (!function_exists("getChannelList"))
{
	function getChannelList($channelList)
	{
		$returnArray = array();
		for ($i = 0; $i < count($channelList); $i++)
		{
			$oneChannel = $channelList[$i];
			$returnArray[$oneChannel['channelId']] = $oneChannel['name'];
		}

		return $returnArray;
	}
}

// 生成tag列表的方法
if (!function_exists("getTagList"))
{
	function getTagList($channelList)
	{
		$returnArray = array();
		for ($i = 0; $i < count($channelList); $i++)
		{
			$oneChannel = $channelList[$i];
			$returnArray[$oneChannel['tag']] = $oneChannel['name'];
		}

		return $returnArray;
	}
}

$config['channellist'] = getChannelList($config['allChannelList']);
$config['taglist'] = getTagList($config['allChannelList']);

$config['channellisthuang'] = array(
    '36'  => '畅游(36)',  
    '37'  => 'googleplay(37)', 
    '38'  => 'UC(38)', 
    '41'  => '德州扑克印尼渠道(41)', 
    '42'  => '德州扑克泰国渠道(42)', 
    '43'  => '德州扑克土耳其渠道(43)', 
    );

$config['channellistx'] = array(
    '0' => 'unknown(0)',
    '1' => 'pokerjoin(1)', //未定义
    '2' => 'anzhi(2)', //安智
    '3' => 'chengdu(3)', //成都
    '4' => 'baichenxun(4)', //百成讯
    '5' => 'yidongmm(5)', //移动mm
    '6' => 'limeiandroid(6)', // 天天牛牛
    '7' => 'yidongjidi(7)', // 移动基地
    '8' => 'unicomfenguang(8)',
    '9' => 'xiaomi(9)', //小米
    '10' => 'pingcoo(10)', // 宾谷
    '11' => 'chinamobilegamebase(11)', //移动游戏基地
    '12' => 'umeng(12)', //友盟
    '13' => 'tianyida(13)', // 天奕达
    '14' => 'baiduduoku(14)', // 百度多酷
    '15' => '联众联运2(15)',
    '16' => 'appstore(16)',
    '17' => '360(17)',
    '18' => '豌豆荚(18)',
    '19' => 'windy(19)',
    '20' => 'shunicom(20)', //上海联通
    '21' => '联众哈尔滨(21)', //联众哈尔滨
    '22' => '福建电信(22)', //联众哈尔滨
    '23' => '冒泡客(23)', //联众哈尔滨
    '24' => '木蚂蚁(24)',
    '25' => '华为(25)',
    '26' => '可可(26)',
    '27' => '360II(27)',
    '28' => 'HIWIFI(28)',
    '29'  => '电信爱游戏(29)',
    '30'  => '银联(30)',
    '31'  => '游果移动mm(31)',     //移动mm
    '32'  => '移动游戏基地(32)',     //移动mm
    '33'  => 'COOLPAD(33)',     //移动mm
    '34'  => '指易付(34)',     //移动mm
    '35'  => '竣网一卡通(35)',     //移动mm
 //   '36'  => '畅游(36)',    
 //   '37'  => 'googleplay(37)', 
  //  '38'  => 'UC(38)', 
    '39'  => '金立(39)', 
    '40'  => 'sinaweb(40)', 
    '44'  => '德州扑克web51(44)', 
    '45' => '华为（朋友）(45)',
    '46' => '华为（朋友变正式）(46)',
    '47' => '联想(47)',
    '48' => '和游戏独立账户(48)',
    '49' => '和游戏wifi万能钥匙(49)',
    '50' => '乐吧渠道(50)',
        //           '999' => '默认（999）',
    
    '36'  => '畅游(36)',    
    '37'  => 'googleplay(37)', 
    '38'  => 'UC(38)', 
    '41'  => '德州扑克印尼渠道(41)', 
    '42'  => '德州扑克泰国渠道(42)', 
    '43'  => '德州扑克土耳其渠道(43)', 
);

$config['channellistxhuang'] = array(
    '36'  => '畅游(36)',    
    '37'  => 'googleplay(37)', 
    '38'  => 'UC(38)', 
    '41'  => '德州扑克印尼渠道(41)', 
    '42'  => '德州扑克泰国渠道(42)', 
    '43'  => '德州扑克土耳其渠道(43)', 
 
    );

$config['paygamelist'] = array(
    '001' => '德州扑克(001)',
    '002' => '扎金花(002)',
    '003' => '掼蛋(003)',
    '004' => '牛牛(004)',
    '005' => '捕鱼(005)',
    '006' => '黄金扎金花(006)',
    '007' => '德州扑克2(007)',
    '008' => '百家乐(008)',
    '009' => '水果机(009)',
    '010' => '大转盘(010)',
    '011' => '斗地主(011)',
    '012' => '港式五张(012)',
    '013' => '新赢三张(013)',
    '014' => '21点(014)',
    '015' => '赢话费扎金花(015)',
    '016' => '域起天天扎金花(016)',
    '017' => '域起快乐扎金花(017)',
    '018' => '欢乐赢三张(018)',
    '019' => '飘三叶(019)',
    '020' => '域起斗地主(020)',
    '021' => '欢乐斗地主(021)',
    '022' => '欢乐飘三叶(022)',
    '023' => '11移动mm德州扑克(023)',
    '024' => '11移动mm斗地主(024)',
    '025' => '11联通斗地主(025)',
    '026' => 'web欢乐赢三张(026)',
    '027' => 'IOS快乐牛牛(027)',
    '028' => 'IOS欢乐牛牛(028)',
    '029' => '二人麻将(029)',
    '030' => '游果牛牛(030)' , 
  //  '031' => '印度扑克(031)' , 
    '032' => 'WEB斗地主(032)' , 
  //  '033' => '德州扑克畅游美元(033)' , 
    '040' => '德州扑克独立版本(040)' , 
    '041' => '增值版斗地主(041)' , 
    '046' => '德州扑克web51(046)' , 
    '047' => '德州扑克IOS国内(047)' , 
    '048' => '增值版斗地主春节临时(048)' , 
    '049' => '单机斗地主 (49)' , 
    '050' => '一起欢乐斗地主(50)' , 
    '051' => '(我是掼蛋王)一起欢乐斗地主(51)' , 
    '053' => '国内德州博豪版本(53)' , 
    '080' => '我是掼蛋王IOS独立版本(80)' , 
    '081' => '我是掼蛋王android独立版本(81)' , 
    '082' => '一起掼蛋android独立版本(82)' , 
    '083' => '一起捕鱼android独立版本(83)' , 
    '084' => '一起捕鱼IOS独立版本(84)' , 
    
    '031' => '印度扑克(031)' , 
    '034' => '德州扑克畅游美元(034)' ,
    '035' => '港式扑克美元(035)' ,
    '036' => '21点美元美元(036)' ,
    '037' => '百家乐美元美元(037)' ,
    '038' => '二人麻将美元(038)' ,
    '042' => '德州扑克印尼版(042)' , 
    '043' => '土耳其Okey(043)' , 
    '044' => '德州扑克泰国(044)' , 
    '045' => '德州扑克土耳其(045)' , 
    '090' => '捕鱼传奇(090)',
    '100' => '新德州(100)',
    '110' => '电玩城(110)',
);

$config['paygamelisthuang'] = array(
    '031' => '印度扑克(031)' , 
    '034' => '德州扑克畅游美元(034)' ,
    '035' => '港式扑克美元(035)' ,
    '036' => '21点美元美元(036)' ,
    '037' => '百家乐美元美元(037)' ,
    '038' => '二人麻将美元(038)' ,
    '042' => '德州扑克印尼版(042)' , 
    '043' => '土耳其Okey(043)' , 
    '044' => '德州扑克泰国(044)' , 
    '045' => '德州扑克土耳其(045)' , 
    );

$config['eventlist'] = array(
    "1" => "牌局赢分(1)",
    "2" => "牌局输分(2)",
    "3" => "购买道具(3)",
    "4" => "出售道具(4)",
    "5" => "购买礼物(5)",
    "6" => "广告墙加分(6)",
    "7" => "无(7)",
    "8" => "赠送筹码(8)",
    "9" => "游戏内购买(9)",
    "10" => "在线奖励(10)",
    "11" => "牌桌奖励(11)",
    "12" => "救济领取(12)",
    "13" => "登录奖励(13)",
    "14" => "大转盘奖励(14)",
    "15" => "水果机奖励(15)",
    "16" => "扎金花洗钱(16)",
    "17" => "玩家充值(17)",
    "18" => "后台加分(18)",
    "19" => "后台减分(19)",
    "20" => "VIP登录奖励(20)",
    "21" => "购买小喇叭(21)",
    "22" => "购买VIP(22)",
    "23" => "赠送筹码服务费(23)",
    "24" => "掉线玩家牌局输赢(24)",
    "25" => "任务奖励(25)",
    "26" => "无(26)",
    "27" => "兑换商品(27)",
    "28" => "无(28)",
    "29" => "签到奖励(29)",
    "30" => "比赛场报名费(30)",
);
$config['eventlists'] = array(
    "12" => "救济领取(12)",
    "13" => "登录奖励(13)",
    "17" => "玩家充值(17)",
    "18" => "后台加分(18)",
    "19" => "后台减分(19)",
    "25" => "任务奖励(25)",
    "27" => "兑换商品(27)",
 );

$config['gamecode'] = array(
    "All(全部10000)" => 10000,
    "德州扑克" => 0,
    "牛牛" => 1,
    //"kBaccarat(2)" => 2,
    "三张牌" => 3,
    //"kSlots(4)" => 4,
    //"kRoulette(5)" => 5,
    "斗地主" => 6,
    //"kStud(7)" => 7,
    //"kGuanDan(8)" => 8,
    //"kBlackJack(9)" => 9,
    //"kNiuNiuQiangZhuang(10)" => 10,
    //"kShiSanZhang(11)" => 11,
    //"kBuYuOL(12)" => 12,
    "捕鱼" => 13,
    //"kMaJiang2P(14)" => 14,
    //"kLKPY(15)" => 15,
  //  "teenpatti(16)" => 16,
    // "kMaJiang(18)" => 18,
     "电玩城" => 19
    // "kDouDiZhuTournament(20)" => 20,
    
);

$config['gamecodeforchoose'] = array(
    "All(全部-1)" => -1,
    "德州扑克" => 0,
    "牛牛" => 1,
    //"kBaccarat(2)" => 2,
    "三张牌" => 3,
   // "kSlots(4)" => 4,
   // "kRoulette(5)" => 5,
    "斗地主" => 6,
  //  "kStud(7)" => 7,
   // "kGuanDan(8)" => 8,
 //   "kBlackJack(9)" => 9,
 //   "kNiuNiuQiangZhuang(10)" => 10,
  //  "kShiSanZhang(11)" => 11,
  //  "kBuYuOL(12)" => 12,
    "捕鱼" => 13,
  //  "kMaJiang2P(14)" => 14,
  //  "kLKPY(15)" => 15,
  //  "teenpatti(16)" => 16,
   //  "MJ4P(18)" => 18,
	"三公" => 24,
     "电玩城" => 19,
    // "teenpatti(16)" => 16, 
);


$config['gamecodehuang'] = array(
   "teenpatti(16)" => 16, 
);


$config['gamefishlist'] = array(
    "All(全部0)" => 0,
    "FishingOnline" => 193
);

$config['gamelist'] = array(
    //  "Unknown" => 0,
    //  "TexasPokerPuTong(德州扑克(普通场))" => 1,
    //  "TexasPokerJiaBei(德州扑克(加倍场))" => 2,
    //  "TexasPokerHuanLe(德州扑克(欢乐场))" => 3,
    "All(全部0)" => 0,
    //"德州扑克(1)" => 1,
    //"百人德州扑克(5)" => 5,
    "牛牛(17)" => 17,
    //"牛牛(18)" => 18,
    "看牌抢庄牛牛(20)" => 20,
    //"百人牛牛(21)" => 21,
    //   "NiuNiuXueZhanDaoDi(牛牛(血战到底))" => 19,
    //  "Baccarat(百家乐)" => 33,
    "三张牌(49)" => 49,
    //"三张牌私人房间(51)" => 51,
    "百人三张(52)" => 52,
    //  "Slots(水果机)" => 65,
    //   "Roulette(大转盘)" => 81,
	"红黑大战(54)" => 54,
    "斗地主-普通场(97)" => 97,
    "斗地主-欢乐场(98)" => 98,
    //   "TournamentDouDiZhuHuanLe(斗地主比赛(欢乐场))" => 99,
    "斗地主-癞子场(101)" => 101,
    //"斗地主PK赛-普通场(100)" => 100,
    //"斗地主slot拉霸赛-普通场(99)" => 99,
   
    //   "BlackJack(二十一点)" => 113,
    //   "Stud(梭哈)" => 129,
//       "GuanDan(掼蛋145)" => 145,
//     "GuanDan(掼蛋146)" => 146,
//     "GuanDan(南京电视台海选赛148)" => 148,
//      "GuanDan(掼蛋免费赛149)" => 149,
    //  "ShiSanZhang(十三张)" => 161,
//     "MJ2P(二人麻将177)" => 177,
//     "MJ4P(四人麻将178)" => 178,
 //   "Teenpatti(印度扑克257)" => 257,
      "FishingOnline(捕鱼OL-193)" => 193,
     // "FishingOnline(捕鱼OL-252)" => 20193,
    // "FishingOnline(捕鱼OL-250)" => 30193,
    // "FishingOnline(捕鱼OL-253)" => 40193,
   //   "LKPY(李逵捕鱼)" => 209,
   // "BuYuOL(捕鱼OL(山东))" => 241
   //  "Teenpatti(印度扑克257)" => 257,
     "电玩城(289)" => 289,
		"马来牛牛(23)" => 23,
		"三公(24)" => 24,
		
);

$config['gamelisthuang'] = array(
    "Teenpatti(印度扑克257)" => 257,
    );

$config['payment_tables'] = array(
    '0001' => array('tbname' => 'CASINOALIPAYRECORD', 'name' => '支付宝(0001)'),
    '0004' => array('tbname' => 'CASINOSHENZHOUFURECORD', 'name' => '神州付(0004)'),
    '0005' => array('tbname' => 'CASINOSANLIULINGRECORD', 'name' => '360(0005)'),
//    '0006' => array('tbname' => 'CASINOWEIPAIRECORD',               'name' => '微派'),
    '0008' => array('tbname' => 'CASINOAPPSTORERECORD', 'name' => '苹果(0008)'),
    '0009' => array('tbname' => 'CASINOJIUYAORECORD', 'name' => '91(0009)'),
    '0010' => array('tbname' => 'CASINOCHINAMOBILERECORD', 'name' => '中国移动应用内计费(0010)'),
    '0011' => array('tbname' => 'CASINOGOOGLEPLAYRECORD', 'name' => 'GooglePlay(0011)'),
    '0012' => array('tbname' => 'CASINOCHINAUNICOMRECORD', 'name' => '联通承泰(0012)'),
    '0013' => array('tbname' => 'CASINOCHINAUNICOMWORECORD', 'name' => '联通沃商城(0013)'),
    '0014' => array('tbname' => 'CASINOYIFUTONGRECORD', 'name' => '易付通(0014)'),
    '0015' => array('tbname' => 'CASINOMOBILEGAMEBASERECORD', 'name' => '移动游戏基地(0015)'),
    '0016' => array('tbname' => 'CASINOTELECOMGAMEBASERECORD', 'name' => '电信游戏基地(0016)'),
    '0017' => array('tbname' => 'CASINOHUAFUBAORECORD', 'name' => '话付宝(0017)'),
    '0018' => array('tbname' => 'CASINOBAIDURECORD', 'name' => '百度(0018)'),
    '0019' => array('tbname' => 'CASINOXIAOMIRECORD', 'name' => '小米(0019)'),
    '0020' => array('tbname' => 'CASINODUOKURECORD', 'name' => '多酷(0020)'),
    '0021' => array('tbname' => 'CASINOTENCENTRECORD', 'name' => '腾讯(0021) '),
    '0022' => array('tbname' => 'CASINOANZHIRECORD', 'name' => '安智(0022)'),
    '0023' => array('tbname' => 'CASINOJIFENGRECORD', 'name' => '机锋(0023)'),
    '0024' => array('tbname' => 'CASINOPPRECORD', 'name' => 'PP(0024)'),
    '0025' => array('tbname' => 'CASINODANGLERECORD', 'name' => '当乐(0025)'),
    '0026' => array('tbname' => 'CASINOKUAIYONGRECORD', 'name' => '快用(0026)'),
    '0027' => array('tbname' => 'CASINOTIANYIKONGJIANRECORD', 'name' => '天翼空间(0027)'),
    '0028' => array('tbname' => 'CASINOLIANTONGYIYIRECORD', 'name' => '联通壹壹(0028)'),
    '0029' => array('tbname' => 'CASINOZHENGGAOYIDONGRECORD', 'name' => '正高移动(0029)'),
    '0030' => array('tbname' => 'CASINOBINGUORECORD', 'name' => '宾果(0030)'),
    '0031' => array('tbname' => 'CASINOJUWANRECORD', 'name' => '聚玩(0031)'),
    '0032' => array('tbname' => 'CASINOJUWANRECORD', 'name' => '聚玩驼陆卡(0032)'),
    '0033' => array('tbname' => 'CASINOYINGHUAXUNFANGRECORD', 'name' => '盈华讯方(0033)'),
    '0034' => array('tbname' => 'CASINOMSHANGRECORD', 'name' => 'M赏(0034)'),
    '0035' => array('tbname' => 'CASINONANJINGTELECOMRECORD', 'name' => '翼支付(0035)'),
    '0036' => array('tbname' => 'CASINOSHENGDARECORD', 'name' => '盛大支付(0036)'),
    '0037' => array('tbname' => 'CASINOSHANGHAILIANTONGRECORD', 'name' => '上海联通(0037)'),
    '0038' => array('tbname' => 'CASINOPAOPAORECORD', 'name' => '冒泡支付(0038)'),
    '0039' => array('tbname' => 'CASINOMUMAYIRECORD', 'name' => '木蚂蚁支付(0039)'),
    '0040' => array('tbname' => 'CASINOHUAWEIRECORD', 'name' => '华为支付(0040)'),
    '0041' => array('tbname' => 'CASINOKEKERECORD',                 'name' => '可可支付(0041)'),
    '0042' => array('tbname' => 'CASINOSANLIULINGIIRECORD',         'name' => '360II(0042)'),
    '0043' => array('tbname' => 'CASINOPAYCHANNEL_43',              'name' => 'HIWIFI(0043)'),
    '0044' => array('tbname' => 'CASINOPAYCHANNEL_44',              'name' => '电信爱游戏(0044)'),
    '0045' => array('tbname' => 'CASINOPAYCHANNEL_45',              'name' => '银联(0045)'),
    '0046' => array('tbname' => 'CASINOPAYCHANNEL_46',              'name' => '移动游戏基地II(0046)'),
    '0047' => array('tbname' => 'CASINOPAYCHANNEL_47',              'name' => 'COOLPAD(0047)'),
    '0048' => array('tbname' => 'CASINOPAYCHANNEL_48',              'name' => '指易付(0048)'),
    '0049' => array('tbname' => 'CASINOPAYCHANNEL_49',              'name' => '竣网一卡通(0049)'),
   // '0050' => array('tbname' => 'CASINOPAYCHANNEL_50',              'name' => '畅游(0050)'),
  //  '0051' => array('tbname' => 'CASINOPAYCHANNEL_51',              'name' => 'googleplay(0051)'),
  //  '0052' => array('tbname' => 'CASINOPAYCHANNEL_52',              'name' => 'fortumo(0052)'),
  //  '0053' => array('tbname' => 'CASINOPAYCHANNEL_53',              'name' => 'uc(0053)'),
   // '0054' => array('tbname' => 'CASINOPAYCHANNEL_54',              'name' => '畅游美元(0054)'),
    '0055' => array('tbname' => 'CASINOPAYCHANNEL_55',              'name' => 'sinaweb(0055)'),
    '0065' => array('tbname' => 'CASINOPAYCHANNEL_65',              'name' => '德州扑克web51(0065)'),
    '0066' => array('tbname' => 'CASINOPAYCHANNEL_66',              'name' => '金立渠道(0066)'),
    '0067' => array('tbname' => 'CASINOPAYCHANNEL_67',              'name' => '联想渠道(0067)'),
    '0068' => array('tbname' => 'CASINOPAYCHANNEL_68',              'name' => '德州扑克国内(0068)'),
    '0069' => array('tbname' => 'CASINOPAYCHANNEL_69',              'name' => '德州扑繁体(0069)'),
    '0070' => array('tbname' => 'CASINOPAYCHANNEL_70',              'name' => '德州扑泰国(0070)'),
    '0071' => array('tbname' => 'CASINOPAYCHANNEL_71',              'name' => '微信支付(0071)'),
    '0072' => array('tbname' => 'CASINOPAYCHANNEL_72',              'name' => '乐吧支付(0072)'),
    '0073' => array('tbname' => 'CASINOPAYCHANNEL_73',              'name' => '钱保支付(0073)'),
    
    '0051' => array('tbname' => 'CASINOPAYCHANNEL_51',              'name' => 'googleplay(0051)'),
    '0052' => array('tbname' => 'CASINOPAYCHANNEL_52',              'name' => 'fortumo(0052)'),
    '0053' => array('tbname' => 'CASINOPAYCHANNEL_53',              'name' => 'uc(0053)'),
    '0054' => array('tbname' => 'CASINOPAYCHANNEL_54',              'name' => '畅游美元(0054)'),
    '0056' => array('tbname' => 'CASINOPAYCHANNEL_56',              'name' => '港式扑克美元(0056)'),
    '0057' => array('tbname' => 'CASINOPAYCHANNEL_57',              'name' => '21点美元(0057)'),
    '0058' => array('tbname' => 'CASINOPAYCHANNEL_58',              'name' => '百家乐美元(0058)'),
    '0059' => array('tbname' => 'CASINOPAYCHANNEL_59',              'name' => '二人麻将美元(0059)'),
    '0060' => array('tbname' => 'CASINOPAYCHANNEL_60',              'name' => '德州扑克印尼googleplay(0060)'),
    '0061' => array('tbname' => 'CASINOPAYCHANNEL_61',              'name' => '土耳其麻将googleplay(0061)'),
    '0062' => array('tbname' => 'CASINOPAYCHANNEL_62',              'name' => '德州扑克泰国googleplay(0062)'),
    '0063' => array('tbname' => 'CASINOPAYCHANNEL_63',              'name' => '德州扑克土耳其googleplay(0063)'),
    '0064' => array('tbname' => 'CASINOPAYCHANNEL_64',              'name' => '印尼德州扑克coda(0064)'),
    
    '0079' => array('tbname' => 'CASINOPAYCHANNEL_79',              'name' => '应用保渠道(0079)'),
    
    '0080' => array('tbname' => 'CASINOPAYCHANNEL_80',              'name' => '百度单机(0080)'),
    '0081' => array('tbname' => 'CASINOPAYCHANNEL_81',              'name' => '百度PC视频(0081)'),
    
);

$config['payment_tableshuang'] = array(
    '0051' => array('tbname' => 'CASINOPAYCHANNEL_51',              'name' => 'googleplay(0051)'),
    '0052' => array('tbname' => 'CASINOPAYCHANNEL_52',              'name' => 'fortumo(0052)'),
    '0053' => array('tbname' => 'CASINOPAYCHANNEL_53',              'name' => 'uc(0053)'),
    '0054' => array('tbname' => 'CASINOPAYCHANNEL_54',              'name' => '畅游美元(0054)'),
    '0056' => array('tbname' => 'CASINOPAYCHANNEL_56',              'name' => '港式扑克美元(0056)'),
    '0057' => array('tbname' => 'CASINOPAYCHANNEL_57',              'name' => '21点美元(0057)'),
    '0058' => array('tbname' => 'CASINOPAYCHANNEL_58',              'name' => '百家乐美元(0058)'),
    '0059' => array('tbname' => 'CASINOPAYCHANNEL_59',              'name' => '二人麻将美元(0059)'),
    '0060' => array('tbname' => 'CASINOPAYCHANNEL_60',              'name' => '德州扑克印尼googleplay(0060)'),
    '0061' => array('tbname' => 'CASINOPAYCHANNEL_61',              'name' => '土耳其麻将googleplay(0061)'),
    '0062' => array('tbname' => 'CASINOPAYCHANNEL_62',              'name' => '德州扑克泰国googleplay(0062)'),
    '0063' => array('tbname' => 'CASINOPAYCHANNEL_63',              'name' => '德州扑克土耳其googleplay(0063)'),
    '0064' => array('tbname' => 'CASINOPAYCHANNEL_64',              'name' => '印尼德州扑克coda(0064)'),

    );


$config['alipay_transfer'] = array(
		array('id' => 1, 'account' => 'aaaaaa@163.com', 'qrcode' => '', 'url' => 'https://qr.alipay.com/aaaaaaaaaaaaaa'),
		array('id' => 2, 'account' => 'bbbbbb@163.com', 'qrcode' => '', 'url' => 'https://qr.alipay.com/bbbbbbbbbbbbbb'),
		);
	

$config['own_pay'] = array(
		PAY_PLATFORM_IMPAY => 'im支付',
		PAY_PLATFORM_PROMOTION => '推广代理充值',
);

$config['yl_pay'] = array(
		PAY_PLATFORM_HAIFUPAY => '海富支付',
		PAY_PLATFORM_CHANGCHENGYUN_BANK => '长城云银联',
		PAY_PLATFORM_JUBAOYUN => '聚宝云',
		PAY_PLATFORM_WEENPAY => 'ween支付',
		PAY_PLATFORM_JSF_BANK => '及时付银联',
);
$config['jd_pay'] = array(
		PAY_PLATFORM_LUYI_JD155 => '路易JD155',
		PAY_PLATFORM_CHANGCHENGYUN_JD => '长城云京东',
		PAY_PLATFORM_PINFU => '品付',
		PAY_PLATFORM_YISHENG_JD => '易生京东',
		PAY_PLATFORM_WEIJD => '微派京东',
);
$config['qq_pay'] = array(
		PAY_PLATFORM_WEENPAY => 'ween支付',
		PAY_PLATFORM_BLKYJF_QQ => '80卡云计费QQ',
		PAY_PLATFORM_LUYI_QQWAP => '路易QQWAP',
		PAY_PLATFORM_CHANGCHENGQQH5=>'长城QQ钱包',
		PAY_PLATFORM_WEIQQ=>'微派QQ钱包', 
		PAY_PLATFORM_LUYI_QQ99 => '路易QQ99',
		PAY_PLATFORM_PINFU => '品付',
		PAY_PLATFORM_JUBAOYUN => '聚宝云',
);

$config['wx_pay'] = array(
		PAY_PLATFORM_CHANGFU => '畅付',
		PAY_PLATFORM_PINFU => '品付',
		PAY_PLATFORM_JUBAOYUN => '聚宝云',
		PAY_PLATFORM_CHANGCHENGYUN_WX => '长城云微信',
		PAY_PLATFORM_DSPAY => '得仕支付',
		PAY_PLATFORM_ZHIHUIFU => '智汇付',
		PAY_PLATFORM_JUHENEW => '新聚合支付',
		PAY_PLATFORM_PFWXSM => '品付微信扫码',
		PAY_PLATFORM_OFDSC => 'OF商城',
);

$config['alipay_pay'] = array(
		PAY_PLATFORM_CHANGCHENGYUN => '长城云',
		PAY_PLATFORM_PAIPAY=>'派支付',
		PAY_PLATFORM_RONGYINPAY => '蓉银支付',
		PAY_PLATFORM_HFT_ZFB => '合付通支付宝',
		PAY_PLATFORM_MOSHANG_ZFB => '陌上支付宝',
		PAY_PLATFORM_YUNBEI_ZFB => '云贝支付宝',
		PAY_PLATFORM_YBNEW_ZFB => '云贝新支付',
		PAY_PLATFORM_WEEN_ZFB => 'WEEN支付宝',
		PAY_PLATFORM_YR_ZFB => '永仁支付宝',
		PAY_PLATFORM_521JB_ZFB => '521jb支付宝',
		PAY_PLATFORM_JKWLKJ => '会昶支付',
		PAY_PLATFORM_BLKYJF => '80卡云计费',
		PAY_PLATFORM_JSF_ZFB => '及时付支付宝',
		PAY_PLATFORM_GXZF => '广讯支付',
		//PAY_PLATFORM_YUFU => '裕付',
		PAY_PLATFORM_PINFU => '品付',
		//PAY_PLATFORM_CHANGFU => '畅付',
		PAY_PLATFORM_ABPAY => '爱贝',
		PAY_PLATFORM_JUBAOYUN => '聚宝云',
		//PAY_PLATFORM_JMPAY => '聚米',
		PAY_PLATFORM_WEIPAY => '微派',
		//PAY_PLATFORM_KAIXIN => '凯新',
		PAY_PLATFORM_ZHONGTIETONG => '中铁通', 
		//PAY_PLATFORM_FANQIE => '番茄支付',
		PAY_PLATFORM_LUYI => '路易支付',
		//PAY_PLATFORM_HUIYI => '汇亿',
		PAY_PLATFORM_ZFB_TRANSFER=>'支付宝转账',
		PAY_PLATFORM_ZFB_TRANSFER_WEB=>'支付宝web转账',
		PAY_PLATFORM_HAIFUPAY => '海富支付',
		PAY_PLATFORM_JFT => '竣付通',
		PAY_PLATFORM_WEIPAY_5 => '微派（5点）',
		PAY_PLATFORM_ZHJH=>'兆行聚合',
);

$config['official_alipay_pay'] = array(
		//PAY_PLATFORM_ZFB_LUOKE => '支付宝洛客',
		// PAY_PLATFORM_ZFB_JUNYING => '支付宝君赢',
		// PAY_PLATFORM_ZFB_ZHIHUI => '支付宝智慧',
		//PAY_PLATFORM_ZFB_QIANKUN => '支付宝乾坤',
		//PAY_PLATFORM_ZFB_ZGY => '支付宝众根源',
		//PAY_PLATFORM_ZFB_YD => '支付宝勇度',
		//PAY_PLATFORM_ZFB_LEIZ => '支付宝雷正',
		//PAY_PLATFORM_ZFB_LONGZ => '支付宝龙泽',
		//PAY_PLATFORM_ZFB_MYW => '支付宝蚂蚁王',
		//PAY_PLATFORM_ZFB_SHDKJ => '支付宝盛恒达科技',
		//PAY_PLATFORM_ZFB_SKLKJ => '支付宝顺科利科技',
		//PAY_PLATFORM_ZFB_HCWLKJ => '支付宝宏潮网络科技',
		//PAY_PLATFORM_ZFB_PXWLKJ => '支付宝鹏兴网络科技',
		//PAY_PLATFORM_ZFB_XWWLKJ => '支付宝兴旺网络科技',
		//PAY_PLATFORM_ZFB_XQXXKJ => '支付宝星祺信息科技',
		//PAY_PLATFORM_ZFB_CYXXKJ => '支付宝长远信息科技',
		//PAY_PLATFORM_ZFB_TSWLKJ => '支付宝天胜网络科技',
		//PAY_PLATFORM_ZFB_JKWLKJ => '支付宝吉凯网络科技',
		//PAY_PLATFORM_ZFB_XHWLKJ => '支付宝星瀚网络科技',
		//PAY_PLATFORM_ZFB_CSXXKJ => '支付宝常胜信息科技',
		//PAY_PLATFORM_ZFB_CHWLKJ => '支付宝晨海网络科技',
		//PAY_PLATFORM_ZFB_HYWLKJ => '支付宝红英网络科技',
		PAY_PLATFORM_ZFB_FBWLKJ => '支付宝风暴网络科技',
		PAY_PLATFORM_ZFB_MYWLKJ => '支付宝明月网络科技',
		PAY_PLATFORM_ZFB_WXWLKJ => '支付宝温馨网络科技',
		//PAY_PLATFORM_ZFB_DETXXKJ => '支付宝达尔特信息科技',
		//PAY_PLATFORM_ZFB_KSYLWLKJ => '支付宝凯盛亚利网络科技',
		PAY_PLATFORM_ZFB_MJXXKJ => '支付宝淼吉信息科技',
	    PAY_PLATFORM_ZFB_YYWLKJ => '支付宝盈悦网络科技',
		PAY_PLATFORM_ZFB_XSWLKJ => '支付宝晓胜网络科技',
		PAY_PLATFORM_ZFB_OTGYWLKJ=>'支付宝欧特格雅网络科技',
		PAY_PLATFORM_ZFB_LGWLKJ => '支付宝流光网络科技',
		PAY_PLATFORM_ZFB_MENJUNWLKJ => '支付宝梦君网络科技',
		PAY_PLATFORM_ZFB_GZJXXXJS => '支付宝爵星信息技术',
);

$config['game_codes'] = array(
		'0' => '游戏种类',
		'999990' => '溜溜游戏',
		'1000' => '平安游戏'
);

//"add_time","pay_success_time"
$config['pay_statics_platforms'] = array(
		PAY_PLATFORM_JUBAOYUN=>'pay_success_time',// 3 聚宝云
		PAY_PLATFORM_HUIONE=>'add_time',// 4 汇旺
		PAY_PLATFORM_YUFU=>'add_time',// 5 裕付
		PAY_PLATFORM_CHANGFU=>'add_time',// 6 畅付云
		PAY_PLATFORM_PINFU=>'add_time',// 11 品付
		PAY_PLATFORM_ZFB_LUOKE=>'pay_success_time',// 12 支付宝洛客
		PAY_PLATFORM_CAIHONG=>'add_time',// 13 彩虹
		PAY_PLATFORM_ZFB_JUNYING=>'pay_success_time',// 14 支付宝君赢
		PAY_PLATFORM_ZFB_ZHIHUI=>'pay_success_time',// 15 支付宝智慧
		PAY_PLATFORM_TMPAY=>'add_time',// 16 TMPay
		PAY_PLATFORM_ABPAY=>'add_time',// 17 爱贝
		PAY_PLATFORM_YUFU_CARD=>'add_time',// 18 裕付卡支付
		PAY_PLATFORM_ZFB_QIANKUN=>'pay_success_time',// 19 支付宝乾坤
		PAY_PLATFORM_ZFB_TRANSFER=>'add_time',// 20 支付宝转账
		PAY_PLATFORM_ZFB_TRANSFER_WEB=>'pay_success_time',// 21 支付宝web转账
		PAY_PLATFORM_CHANGFU_CARD=>'add_time',// 22 畅付卡支付
		PAY_PLATFORM_ZFB_ZGY=>'pay_success_time',// 23 支付宝众根源
		PAY_PLATFORM_ZFB_YD=>'pay_success_time',// 24 支付宝勇度
		PAY_PLATFORM_ZFB_LEIZ=>'pay_success_time',// 25 支付宝雷正
		PAY_PLATFORM_ZFB_LONGZ=>'pay_success_time',// 26 支付宝龙泽
		PAY_PLATFORM_ZFB_MYW=>'pay_success_time',// 27 支付宝蚂蚁王
		PAY_PLATFORM_ZFB_SHDKJ=>'pay_success_time',// 28 支付宝盛恒达科技
		PAY_PLATFORM_ZFB_SKLKJ=>'pay_success_time',// 29 支付宝顺科利科技
		PAY_PLATFORM_JMPAY=>'add_time',// 30 聚米支付
		PAY_PLATFORM_WEIPAY=>'pay_success_time',//31 微派支付-到帐时间
		PAY_PLATFORM_KAIXIN=>'add_time',// 32 凯新支付
		PAY_PLATFORM_ZHONGTIETONG=>'add_time',// 33 中铁通付
		PAY_PLATFORM_ZHONGTIETONG_QQ=>'add_time',// 34 中铁通付qq
		PAY_PLATFORM_FANQIE=>'pay_success_time',// 35 番茄支付-到帐时间
		PAY_PLATFORM_LUYI=>'pay_success_time',// 36 路易支付
		PAY_PLATFORM_CHANGCHENGYUN=>'add_time',// 37 长城云支付
		PAY_PLATFORM_ZFB_HYXXKJ=>'pay_success_time',// 38 支付宝汇亿信息科技
		PAY_PLATFORM_ZFB_HCWLKJ=>'pay_success_time',// 39 支付宝宏潮网络科技
		PAY_PLATFORM_ZFB_PXWLKJ=>'pay_success_time',// 40 支付宝鹏兴网络科技
		PAY_PLATFORM_ZFB_XWWLKJ=>'pay_success_time',// 41 支付宝兴旺网络科技
		PAY_PLATFORM_ZFB_XQXXKJ=>'pay_success_time',// 42 支付宝星祺信息科技
		PAY_PLATFORM_ZFB_CYXXKJ=>'pay_success_time',// 43 支付宝长远信息科技
		PAY_PLATFORM_ZFB_TSWLKJ=>'pay_success_time',// 44 支付宝天胜网络科技
		PAY_PLATFORM_ZFB_JKWLKJ=>'pay_success_time',// 45 支付宝吉凯网络科技
		PAY_PLATFORM_ZFB_XHWLKJ=>'pay_success_time',// 46 支付宝星瀚网络科技
		PAY_PLATFORM_JUHE=>'pay_success_time',// 47聚合
		PAY_PLATFORM_HUIYI=>'pay_success_time',// 48汇亿
		PAY_PLATFORM_LUYI_QQWAP=>'pay_success_time',// 49路易QQWAP
		PAY_PLATFORM_ZFB_CSXXKJ=>'pay_success_time',// 50支付宝常胜信息科技
		PAY_PLATFORM_CHANGCHENGQQH5=>'add_time',// 51 长城QQ钱包
		PAY_PLATFORM_HAIFUPAY=>'add_time',//52 海富支付
		PAY_PLATFORM_ZFB_CHWLKJ=>'pay_success_time',//53 支付宝晨海网络科技
		PAY_PLATFORM_ZFB_HYWLKJ=>'pay_success_time',//54 支付宝红英网络科技
		PAY_PLATFORM_ZFB_FBWLKJ=>'pay_success_time',//55 支付宝风暴网络科技
		PAY_PLATFORM_ZFB_MYWLKJ=>'pay_success_time',//56 支付宝明月网络科技
		PAY_PLATFORM_ZFB_WXWLKJ=>'pay_success_time',//57 支付宝温馨网络科技
		PAY_PLATFORM_LUYI_QQ99=>'pay_success_time',//路易QQ99
		PAY_PLATFORM_WEIQQ=>'pay_success_time',// 60 微派QQ
		99=>'add_time',
		100=>'add_time',
);

$config['pay_statics_timedelay'] = array(
		//PAY_PLATFORM_CHANGCHENGYUN=>4,//37 长城云支付
);


date_default_timezone_set("Asia/Shanghai");
/* End of file config.php */
/* Location: ./application/config/config.php */
